[package]
name = "models"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
json = { path = "../json", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }
protocol = { path = "../protocol", version = "0.0.0" }

anyhow = "*"
base64 = "*"
bytes = "*"
caseless = "0.2.1"
humantime-serde = "*"
lazy_static = "*"
pathfinding = "*"
percent-encoding = "*"
prost = "*"
regex = "*"
rusqlite = { version = "*", features = ["bundled-full"] }
schemars = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*", features = ["raw_value"] }
serde_with = "*"
superslice = "*"
unicode-normalization = "0.1.19"
url = "*"
uuid = { version = "*", features = ["serde"] }
validator = { version = "*", features = ["derive"] }

[dev-dependencies]
insta = "*"
itertools = "*"
serde_yaml = "*"
