[package]
name = "models"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
# NOTE(johnny): DO NOT add proto-flow or proto-gazette to this crate.
# Users shouldn't _have_ to bring in all of our protobuf types as well.
# Instead, consider the `assemble` crate for models <=> protobuf conversions.
doc = { path = "../doc" }
json = { path = "../json" }
labels = { path = "../labels" }


caseless = { workspace = true }
humantime-serde = { workspace = true }
lazy_static = { workspace = true }
pathfinding = { workspace = true }
regex = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
superslice = { workspace = true }
unicode-normalization = { workspace = true }
url = { workspace = true }
validator = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
itertools = { workspace = true }
serde_yaml = { workspace = true }
