[package]
name = "models"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
# NOTE(johnny): DO NOT add proto-flow or proto-gazette to this crate.
# Users shouldn't _have_ to bring in all of our protobuf types as well.
# Instead, consider the `assemble` crate for models <=> protobuf conversions.
doc = { path = "../doc", version = "0.0.0" }
json = { path = "../json", version = "0.0.0" }
labels = { path = "../labels", version = "0.0.0" }


caseless = "*"
humantime-serde = "*"
lazy_static = "*"
pathfinding = "*"
regex = "*"
schemars = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*", features = ["raw_value"] }
superslice = "*"
unicode-normalization = "*"
url = "*"
validator = { version = "*", features = ["derive"] }

[dev-dependencies]
insta = "*"
itertools = "*"
serde_yaml = "*"
