[package]
name = "catalog"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
json = { path = "../json", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }

caseless = "*"
humantime-serde = "*"
include_dir = { version = "*", default-features = false }
itertools = "*"
log = "*"
regex = "*"
reqwest = { version = "*", default-features = false, features = ["blocking", "rustls-tls"] }
rusqlite = { version = "*", features = ["bundled", "collation", "column_decltype", "functions", "serde_json", "url"] }
schemars = "*"
serde = { version = "*", features = ["derive"] }
serde_json = { version =  "*", features = ["raw_value"] }
serde_yaml = "*"
strsim = "*"
tempfile = "*"
thiserror = "*"
unicode-normalization = "*"
url = "*"
yaml-merge-keys = { version = "*", features = ["serde_yaml"] }

[dev-dependencies]
protocol = { path = "../protocol", version = "0.0.0" }

insta = "*"
pretty_env_logger = "*"