[package]
name = "proto-gazette"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[lib]
# The formatting of the generated code comments changed slightly in prost 0.11,
# which results in some comments containing indented sections that are mistaken
# for code blocks, causing doc tests to fail. We don't actually have any doc
# tests in this crate, so they are explicitly disabled.
doctest = false

[dependencies]
bytes = { workspace = true }
pbjson = { workspace = true }
pbjson-types = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[build-dependencies]
proto-build = { path = "../proto-build", optional = true }

pbjson-build = { workspace = true, optional = true }
prost-build = { workspace = true, optional = true }

[features]
default = []
generate = ["proto-build", "pbjson-build", "prost-build"]