[package]
name = "proto-convert"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
proto-flow = { path = "../proto-flow" }
connector-protocol = { path = "../connector-protocol" }
tuple = { path = "../tuple" }

anyhow = { workspace = true }
base64 = { workspace = true }
hex = { workspace = true }
prost = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
