#!/usr/bin/env bash
set -euo pipefail

#MISE description="Run catalog tests"
#MISE depends=["build:connector-musl-bin", "build:rocksdb"]

cargo build -p flowctl
mise run build:bindings

go build -tags libsqlite3 -o ${HOME}/go/bin/flowctl-go ./go/flowctl-go

PATH=${PATH}:${HOME}/cargo-target/debug/:${HOME}/cargo-target/$(uname -m)-unknown-linux-musl/debug/ \
  ${HOME}/go/bin/flowctl-go test --source examples/flow.yaml