#!/usr/bin/env bash
# POC teardown: reverse poc-up.sh, and assert the box is clean afterwards (G8).
#
# `mise run local:stop` does none of this. It stops only user units, deletes env
# files matching *-<stack>.env and *-<cluster>*.env (which reactor-sandbox.env
# does not), and leaves root's podman store alone.
#
# Idempotent and safe to run against a partial setup: every step tolerates its
# subject already being gone.
#
# Run under mise: mise exec -- spike/tasks/poc-down.sh
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/poc-common.sh"

POC_FAILURES=0

step "reactor: remove the root units"
sudo systemctl stop "$POC_ROOT_UNIT" "$POC_SIDECAR_ROOT_UNIT" 2>/dev/null || true
sudo rm -f "$POC_ROOT_UNIT_PATH" "$POC_SIDECAR_ROOT_UNIT_PATH"
sudo systemctl daemon-reload
echo "removed $POC_ROOT_UNIT_PATH and $POC_SIDECAR_ROOT_UNIT_PATH"

step "reactor: restore the stack's user units"
systemctl --user unmask "$POC_USER_UNIT" "$POC_SIDECAR_USER_UNIT" 2>/dev/null || true
rm -f "$POC_SANDBOX_ENV"
systemctl --user daemon-reload
# Started only if the stack is still up: their env files are regenerated by
# local:reactor and deleted by local:stop, so absence means there is no stack to
# rejoin. The sidecar goes first; the reactor refuses runtime-v2 without it.
if [ -f "$POC_REACTOR_ENV" ]; then
    systemctl --user start "$POC_SIDECAR_USER_UNIT" "$POC_USER_UNIT"
    echo "unmasked and started $POC_SIDECAR_USER_UNIT and $POC_USER_UNIT"
else
    echo "unmasked both units (stack is down; not started)"
fi

step "agent: drop the connector-timeout override"
rm -f "$POC_AGENT_DROPIN"
rmdir "$(dirname "$POC_AGENT_DROPIN")" 2>/dev/null || true
systemctl --user daemon-reload
systemctl --user restart "$POC_AGENT_UNIT" 2>/dev/null || true

step "control plane: re-enable the stack's ops tasks"
# Best effort: after a `supabase db reset` these rows no longer exist, and there
# is nothing to restore.
if poc_psql -c 'select 1' >/dev/null 2>&1; then
    poc_ops_disable false || echo "could not re-enable ops tasks; see above" >&2
else
    echo "control plane is not reachable; skipping"
fi

step "containers and reactor directories"
mapfile -t stale < <(sudo podman ps -a --filter 'name=^f[sc]_' --format '{{.Names}}')
if [ "${#stale[@]}" -gt 0 ]; then
    printf 'removing %d container(s):\n' "${#stale[@]}"
    printf '  %s\n' "${stale[@]}"
    sudo podman rm -f "${stale[@]}" >/dev/null
fi
mapfile -t dirs < <(sudo find "$SPIKE_REACTOR_DIR" -mindepth 1 -maxdepth 1 -name 'fs_*')
if [ "${#dirs[@]}" -gt 0 ]; then
    printf 'removing %d reactor director(ies)\n' "${#dirs[@]}"
    sudo rm -rf "${dirs[@]}"
fi
sudo rm -f "$SPIKE_REACTOR_DIR/$POC_POLICY"

step "G8: the box is clean"
left="$(sudo podman ps -a --filter 'name=^f[sc]_' --format '{{.Names}}' | tr '\n' ' ')"
if [ -z "$left" ]; then
    ok "no fs_/fc_ containers remain"
else
    fail "containers remain: $left"
fi

left="$(sudo find "$SPIKE_REACTOR_DIR" -mindepth 1 -maxdepth 1 -name 'fs_*' -printf '%f ')"
if [ -z "$left" ]; then
    ok "no fs_* directories remain in $SPIKE_REACTOR_DIR"
else
    fail "directories remain: $left"
fi

for unit in "$POC_USER_UNIT" "$POC_SIDECAR_USER_UNIT"; do
    if systemctl --user is-enabled "$unit" 2>/dev/null | grep -q masked; then
        fail "$unit is still masked"
    else
        ok "$unit is not masked"
    fi
done

left=""
for path in "$POC_ROOT_UNIT_PATH" "$POC_SIDECAR_ROOT_UNIT_PATH"; do
    [ -e "$path" ] && left="$left $path"
done
if [ -z "$left" ]; then
    ok "the root units are gone"
else
    fail "root units remain:$left"
fi

# The work dir is left alone: it holds the published specs, which are worth
# reading after a failed run. Remove it by hand when done.
printf '\n'
if [ "$POC_FAILURES" -ne 0 ]; then
    printf 'poc-down.sh: %d failure(s)\n' "$POC_FAILURES" >&2
    exit 1
fi
echo "poc-down.sh: ok ($POC_WORK_DIR left in place)"
