
[package]
name = "dekaf-connector"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
avro = { path = "../avro" }
models = { path = "../models" }
proto-flow = { path = "../proto-flow" }
coroutines = { path = "../coroutines" }
unseal = { path = "../unseal" }

anyhow = { workspace = true }
futures = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
