[package]
name = "connector-init"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-connector-init"
path = "src/main.rs"

[dependencies]
connector-protocol = { path = "../connector-protocol" }
ops = { path = "../ops" }
proto-convert = { path = "../proto-convert" }
proto-flow = { path = "../proto-flow" }
proto-grpc = { path = "../proto-grpc", features = [
    "capture_server",
    "materialize_server",
] }

anyhow = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
prost = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
time = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
warp = { workspace = true }
libc = { workspace = true }
nix = { workspace = true }
procfs = { workspace = true }
rlimit = { workspace = true }
rtnetlink = { workspace = true }
ipnetwork = { workspace = true }
ifstructs = { workspace = true }
pin-project = { workspace = true }
os_pipe = { workspace = true }
tokio-vsock = { workspace = true }
derive_builder = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
