[package]
name = "guest-init"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-guest-init"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
libc = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }
