[package]
name = "connector"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
async-process = { path = "../async-process" }
connector-init = { path = "../connector-init" }
dekaf-connector = { path = "../dekaf-connector" }
derive-sqlite = { path = "../derive-sqlite" }
iam-auth = { path = "../iam-auth" }
locate-bin = { path = "../locate-bin" }
models = { path = "../models" }
ops = { path = "../ops" }
proto-flow = { path = "../proto-flow" }
proto-gazette = { path = "../proto-gazette" }
proto-grpc = { path = "../proto-grpc", features = [
    "capture_client",
    "connector_client",
    "connector_server",
    "derive_client",
    "materialize_client",
] }
service-kit = { path = "../service-kit" }
tokens = { path = "../tokens" }
unseal = { path = "../unseal" }

anyhow = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
prost = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tokio = { workspace = true, features = ["macros", "test-util"] }
