[package]
name = "flow-worker"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
catalog = { path = "../catalog", version = "0.0.0" }
derive = { path = "../derive", version = "0.0.0" }
doc = { path = "../doc", version = "0.0.0" }
protocol = { path = "../protocol", version = "0.0.0" }
serve = { path = "../serve", version = "0.0.0" }

anyhow = "*"
futures = "*"
hyper = "*"
libc = "*"
log = "*"
pretty_env_logger = "*"
rocksdb = "*"
structopt = "*"
tokio = { version = "0.2", features = ["full"] }
tower = "*"