use super::Lsn;
use super::block::BlockMeta;
use proto_flow::shuffle;
use proto_gazette::uuid;
use std::collections::HashMap;

/// Immutable log configuration: session identity and member topology.
/// Set once during Log startup and never modified.
pub struct Topology {
    /// Unique identifier for this session, generated by the Session actor.
    /// Used as a tracing correlation value for distributed RPCs/logs.
    pub session_id: u32,
    /// Ordered member topology: each member owns a disjoint key range.
    pub members: Vec<shuffle::Member>,
    /// Index of this Log RPC within `members`.
    pub log_member_index: u32,
    /// Disk backlog threshold in bytes before engaging back-pressure.
    pub disk_backlog_threshold: u64,
}

/// Target ceiling for accumulated doc bytes before forcing a block flush.
const BLOCK_BYTES_THRESHOLD: usize = 1024 * 1024;

/// Accumulates document entries into a block, assigning block-internal IDs
/// for journals and producers as they are encountered.
pub struct BlockState {
    /// Journal-name-to-bid map for the block being accumulated.
    journals: HashMap<String, u16>,
    /// Producer-to-bid map for the block being accumulated.
    producers: HashMap<uuid::Producer, u16>,
    /// Entries accumulating for the current block.
    entries: Vec<(BlockMeta, i64, bytes::Bytes, bytes::Bytes)>,
    /// Total byte count of doc_archived in current entries.
    entries_bytes: usize,
}

impl std::fmt::Debug for BlockState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BlockState")
            .field("entries", &self.entries.len())
            .field("entries_bytes", &self.entries_bytes)
            .field("journals", &self.journals.len())
            .field("producers", &self.producers.len())
            .finish()
    }
}

impl std::fmt::Debug for FlushState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FlushState")
            .field("flushed_lsn", &self.flushed_lsn)
            .field("flush_in_flight", &self.flush_in_flight)
            .field("pending_request", &self.pending_request.len())
            .field("next_pending_flush", &self.next_pending_flush.len())
            .field("pending_response", &self.pending_response.len())
            .finish()
    }
}

impl BlockState {
    pub fn new() -> Self {
        Self {
            journals: HashMap::new(),
            producers: HashMap::new(),
            entries: Vec::new(),
            entries_bytes: 0,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Whether the block has reached capacity and should be flushed.
    /// True when accumulated bytes exceed the threshold (common), or when entries
    /// hits the 65,536 length cap (rare or never, requires tiny documents).
    pub fn is_full(&self) -> bool {
        self.entries_bytes >= BLOCK_BYTES_THRESHOLD || self.entries.len() == 1 << 16
    }

    /// Accumulate an append into the current block.
    /// Assigns journal and producer BIDs, builds BlockMeta, and pushes the entry.
    pub fn accumulate(
        &mut self,
        journal_name: &str,
        producer: uuid::Producer,
        append: &shuffle::log_request::Append,
    ) {
        // Assign or look up journal bid (query by reference to avoid allocating on hit).
        let journal_bid = if let Some(&bid) = self.journals.get(journal_name) {
            bid
        } else {
            let bid = self.journals.len() as u16;
            self.journals.insert(journal_name.to_string(), bid);
            bid
        };

        // Assign or look up producer bid.
        let next_pbid = self.producers.len() as u16;
        let producer_bid = *self.producers.entry(producer).or_insert(next_pbid);

        let meta = BlockMeta {
            binding: append.binding as u16,
            journal_bid,
            producer_bid,
            flags: if append.valid { 0x0001 } else { 0 },
            clock: append.clock,
        };

        self.entries_bytes += append.doc_archived.len();
        self.entries.push((
            meta,
            append.begin_offset,
            append.packed_key.clone(),
            append.doc_archived.clone(),
        ));
    }

    /// Take all accumulated block state for flush handoff, resetting for next block.
    pub fn take(
        &mut self,
    ) -> (
        HashMap<String, u16>,
        HashMap<uuid::Producer, u16>,
        Vec<(BlockMeta, i64, bytes::Bytes, bytes::Bytes)>,
    ) {
        self.entries_bytes = 0;
        (
            std::mem::take(&mut self.journals),
            std::mem::take(&mut self.producers),
            std::mem::take(&mut self.entries),
        )
    }
}

/// Flush lifecycle state machine for the Log actor.
///
/// Tracks whether a flush is in-flight, routes incoming Flush requests
/// to the appropriate queue, and processes flush completions.
pub struct FlushState {
    /// LSN of the most recently completed flush.
    flushed_lsn: Lsn,
    /// Whether a background flush task is currently running.
    flush_in_flight: bool,
    /// Slice index and cycle awaiting the current flush completion.
    pending_request: Vec<(usize, u64)>,
    /// Slice index and cycle awaiting completion of the *next* flush
    /// after the current one. Non-empty only while a flush is underway.
    next_pending_flush: Vec<(usize, u64)>,
    /// Completed flushes awaiting send of their Flushed response.
    /// Each entry is (member_index, cycle, flushed_lsn).
    pending_response: Vec<(usize, u64, Lsn)>,
}

impl FlushState {
    pub fn new() -> Self {
        Self {
            flushed_lsn: Lsn::ZERO,
            flush_in_flight: false,
            pending_request: Vec::new(),
            next_pending_flush: Vec::new(),
            pending_response: Vec::new(),
        }
    }

    pub fn flush_in_flight(&self) -> bool {
        self.flush_in_flight
    }

    #[cfg(test)]
    pub fn flushed_lsn(&self) -> Lsn {
        self.flushed_lsn
    }

    /// Whether there are pending flush requests that need a flush to start.
    pub fn has_pending_request(&self) -> bool {
        !self.pending_request.is_empty()
    }

    /// Route a Flush request based on current state.
    ///
    /// Routing depends on two dimensions:
    /// - Whether a flush is currently in-flight
    /// - Whether there are buffered block entries not yet covered by a flush
    pub fn on_flush(&mut self, member_index: usize, cycle: u64, block_is_empty: bool) {
        if self.flush_in_flight {
            if block_is_empty {
                // Flush is in-flight and no new entries: covered by in-flight flush.
                self.pending_request.push((member_index, cycle));
            } else {
                // Flush is in-flight AND we have new entries not covered by it.
                // Must wait for the *next* flush after the current one completes.
                self.next_pending_flush.push((member_index, cycle));
            }
        } else if block_is_empty {
            // Not flushing and no entries: already trivially flushed.
            self.pending_response
                .push((member_index, cycle, self.flushed_lsn));
        } else {
            // Not flushing but have entries: must await a future flush.
            self.pending_request.push((member_index, cycle));
        }
    }

    /// Mark that a flush has started (writer moved into background task).
    pub fn start_flush(&mut self) {
        debug_assert!(!self.flush_in_flight);
        self.flush_in_flight = true;
    }

    /// Process a flush completion: restore state, drain pending, and swap next_pending.
    pub fn on_flushed(&mut self, flushed_lsn: Lsn) {
        debug_assert!(self.flush_in_flight);
        self.flush_in_flight = false;
        self.flushed_lsn = flushed_lsn;

        for (slice_idx, cycle) in self.pending_request.drain(..) {
            self.pending_response
                .push((slice_idx, cycle, self.flushed_lsn));
        }
        std::mem::swap(&mut self.pending_request, &mut self.next_pending_flush);
    }

    /// Peek at the last completed flush response (LIFO order).
    pub fn peek_pending_response(&self) -> Option<&(usize, u64, Lsn)> {
        self.pending_response.last()
    }

    /// Pop the last completed flush response (LIFO order).
    pub fn pop_pending_response(&mut self) -> Option<(usize, u64, Lsn)> {
        self.pending_response.pop()
    }
}

#[cfg(test)]
mod test {
    use super::*;

    fn append(
        binding: u16,
        clock: u64,
        valid: bool,
        offset: i64,
        doc: &[u8],
    ) -> shuffle::log_request::Append {
        shuffle::log_request::Append {
            binding: binding as u32,
            clock,
            valid,
            begin_offset: offset,
            packed_key: bytes::Bytes::from_static(b"k"),
            doc_archived: bytes::Bytes::copy_from_slice(doc),
            ..Default::default()
        }
    }

    #[test]
    fn test_block_lifecycle() {
        let prod_1 = uuid::Producer([0, 0, 0, 0, 0, 1]);
        let prod_2 = uuid::Producer([0, 0, 0, 0, 0, 2]);
        let mut block = BlockState::new();
        assert!(block.is_empty());
        assert!(!block.is_full());

        fn last_meta(block: &BlockState) -> &BlockMeta {
            &block.entries.last().unwrap().0
        }

        // First append assigns BIDs 0/0; same journal+producer reuses them.
        block.accumulate(
            "journals/alpha",
            prod_1,
            &append(0, 100, true, 0, b"doc_a_content"),
        );
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid,
                last_meta(&block).flags
            ),
            (0, 0, 0x0001)
        );

        block.accumulate(
            "journals/alpha",
            prod_1,
            &append(1, 200, false, 100, b"doc_b"),
        );
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid,
                last_meta(&block).flags
            ),
            (0, 0, 0)
        );

        // New journal + producer get new BIDs.
        block.accumulate(
            "journals/beta",
            prod_2,
            &append(0, 100, true, 0, b"doc_a_content"),
        );
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid
            ),
            (1, 1)
        );

        assert!(!block.is_empty());
        insta::assert_debug_snapshot!(
            &block
                .entries
                .iter()
                .map(|(m, off, _, _)| (m, off))
                .collect::<Vec<_>>()
        );

        // take() returns accumulated state and resets.
        let (journals, producers, entries) = block.take();
        assert_eq!((journals.len(), producers.len(), entries.len()), (2, 2, 3));
        assert!(block.is_empty());
        assert!(!block.is_full());

        // Byte threshold triggers is_full.
        block.accumulate(
            "j/a",
            prod_1,
            &append(0, 1, true, 0, &vec![0u8; BLOCK_BYTES_THRESHOLD - 1]),
        );
        assert!(!block.is_full());
        block.accumulate("j/a", prod_1, &append(0, 2, true, 0, b"x"));
        assert!(block.is_full());

        // Entry and BID-space exhaustion also triggers is_full.
        let mut block = BlockState::new();
        for i in 0..(1 << 16) {
            block.accumulate(&format!("j/{i}"), prod_1, &append(0, 1, true, 0, b"x"));
        }
        assert!(block.is_full());
    }

    #[test]
    fn test_flush_state_machine() {
        let mut flush = FlushState::new();
        let drain = |f: &mut FlushState| {
            std::iter::from_fn(|| f.pop_pending_response()).collect::<Vec<_>>()
        };

        // No inflight + empty block: immediately resolved.
        flush.on_flush(0, 0, true);
        assert_eq!(flush.pop_pending_response(), Some((0, 0, Lsn::ZERO)));
        assert!(!flush.has_pending_request());

        // No inflight + non-empty block: queued to pending_flush.
        flush.on_flush(0, 1, false);
        flush.on_flush(1, 1, false);
        assert!(flush.has_pending_request());
        assert_eq!(flush.pop_pending_response(), None);

        // Start flush cycle 1.
        flush.start_flush();
        assert!(flush.flush_in_flight());

        // Inflight + empty block: covered by current flush → pending_flush.
        flush.on_flush(3, 1, true);

        // Inflight + non-empty block: needs next flush → next_pending_flush.
        flush.on_flush(4, 2, false);
        flush.on_flush(5, 2, false);

        // Complete flush cycle 1.
        flush.on_flushed(Lsn::new(1, 0));
        assert!(!flush.flush_in_flight());
        assert_eq!(flush.flushed_lsn(), Lsn::new(1, 0));

        // Slices 0, 1, 3 (all covered by cycle 1) are now pending_flushed.
        insta::assert_debug_snapshot!("first_batch", drain(&mut flush));

        // Slices 4, 5 (from next_pending) have swapped into pending_flush.
        assert!(flush.has_pending_request());

        // Flush cycle 2.
        flush.start_flush();
        flush.on_flushed(Lsn::new(1, 1));

        insta::assert_debug_snapshot!("second_batch", drain(&mut flush));
        assert!(!flush.has_pending_request());
    }
}
