use super::Lsn;
use super::block::BlockMeta;
use proto_flow::shuffle;
use proto_gazette::uuid;
use std::collections::HashMap;

/// Immutable log configuration: session identity and shard topology.
/// Set once during Log startup and never modified.
pub struct Topology {
    /// Unique identifier for this session, generated by the Session actor.
    /// Used as a tracing correlation value for distributed RPCs/logs.
    pub session_id: u32,
    /// Ordered shard topology: each shard owns a disjoint key range.
    pub shards: Vec<shuffle::Shard>,
    /// Priorities of the session's lanes, in descending order. Slices are
    /// indexed by lane then shard: that of lane `l` at shard `s` is
    /// `l * shards.len() + s`.
    pub priorities: Vec<i32>,
    /// Index of this Log RPC within `shards`.
    pub log_shard_index: u32,
}

impl Topology {
    /// Shard and lane priority of the Slice at index `slice`.
    pub fn slice(&self, slice: usize) -> (&shuffle::Shard, i32) {
        let shard_count = self.shards.len();
        (
            &self.shards[slice % shard_count],
            self.priorities[slice / shard_count],
        )
    }
}

/// On-disk backlog of a Log's sealed segments, which engages back-pressure of
/// the merge at `limit` bytes and releases it at half of `limit` (hysteresis).
#[derive(Debug)]
pub struct DiskState {
    /// Aggregate on-disk bytes across all living sealed segments.
    bytes: u64,
    /// Shuffle disk limit in bytes before engaging back-pressure.
    /// Sourced per-task from the shard's labeling, or the Service default.
    limit: u64,
    back_pressure: bool,
}

impl DiskState {
    pub fn new(limit: u64) -> Self {
        Self {
            bytes: 0,
            limit,
            back_pressure: false,
        }
    }

    pub fn bytes(&self) -> u64 {
        self.bytes
    }

    /// Whether back-pressure is engaged, pausing the merge.
    pub fn back_pressure(&self) -> bool {
        self.back_pressure
    }

    pub fn on_sealed(&mut self, size: u64) {
        self.bytes += size;

        if self.bytes >= self.limit {
            self.back_pressure = true;
        }
    }

    pub fn on_reclaimed(&mut self, reclaimed: u64) {
        self.bytes = self
            .bytes
            .checked_sub(reclaimed)
            .expect("disk_backlog_bytes underflow");

        if self.back_pressure && self.bytes < self.limit / 2 {
            self.back_pressure = false;
        }
    }
}

/// Target ceiling for accumulated doc bytes before forcing a block flush.
const BLOCK_BYTES_THRESHOLD: usize = 1024 * 1024;

/// Accumulates document entries into a block, assigning block-internal IDs
/// for journals and producers as they are encountered.
pub struct BlockState {
    /// Journal-name-to-bid map for the block being accumulated.
    journals: HashMap<String, u16>,
    /// Producer-to-bid map for the block being accumulated.
    producers: HashMap<uuid::Producer, u16>,
    /// Entries accumulating for the current block.
    entries: Vec<(BlockMeta, u32, bytes::Bytes, bytes::Bytes)>,
    /// Total byte count of doc_archived in current entries.
    entries_bytes: usize,
}

impl std::fmt::Debug for BlockState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("BlockState")
            .field("entries", &self.entries.len())
            .field("entries_bytes", &self.entries_bytes)
            .field("journals", &self.journals.len())
            .field("producers", &self.producers.len())
            .finish()
    }
}

impl BlockState {
    pub fn new() -> Self {
        Self {
            journals: HashMap::new(),
            producers: HashMap::new(),
            entries: Vec::new(),
            entries_bytes: 0,
        }
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    /// Whether the block has reached capacity and should be flushed.
    /// True when accumulated bytes exceed the threshold (common), or when entries
    /// hits the 65,536 length cap (rare or never, requires tiny documents).
    pub fn is_full(&self) -> bool {
        self.entries_bytes >= BLOCK_BYTES_THRESHOLD || self.entries.len() == 1 << 16
    }

    /// Accumulate an append into the current block.
    /// Assigns journal and producer BIDs, builds BlockMeta, and pushes the entry.
    pub fn accumulate(
        &mut self,
        journal_name: &str,
        producer: uuid::Producer,
        append: &shuffle::log_request::Append,
    ) {
        // Assign or look up journal bid (query by reference to avoid allocating on hit).
        let journal_bid = if let Some(&bid) = self.journals.get(journal_name) {
            bid
        } else {
            let bid = self.journals.len() as u16;
            self.journals.insert(journal_name.to_string(), bid);
            bid
        };

        // Assign or look up producer bid.
        let next_pbid = self.producers.len() as u16;
        let producer_bid = *self.producers.entry(producer).or_insert(next_pbid);

        let meta = BlockMeta {
            binding: append.binding as u16,
            journal_bid,
            producer_bid,
            flags: append.flags as u16,
            clock: append.clock,
        };

        self.entries.push((
            meta,
            append.source_byte_length,
            append.packed_key.clone(),
            append.doc_archived.clone(),
        ));
        self.entries_bytes += append.doc_archived.len();
    }

    /// Take all accumulated block state for flush handoff, resetting for next block.
    pub fn take(
        &mut self,
    ) -> (
        HashMap<String, u16>,
        HashMap<uuid::Producer, u16>,
        Vec<(BlockMeta, u32, bytes::Bytes, bytes::Bytes)>,
    ) {
        self.entries_bytes = 0;
        (
            std::mem::take(&mut self.journals),
            std::mem::take(&mut self.producers),
            std::mem::take(&mut self.entries),
        )
    }
}

/// Flush accounting of the Log actor, by block number.
///
/// Blocks are numbered from one as their flushes start, and flushes complete
/// in order. A Slice's flush request awaits the accumulating block if it's
/// non-empty, and otherwise the last-started block, which may already be
/// complete. A Slice has at most one flush request outstanding.
#[derive(Debug)]
pub struct FlushState {
    /// Number of blocks whose flush has started.
    /// The accumulating block is `started + 1`.
    started: u64,
    /// Number of blocks whose flush has completed.
    completed: u64,
    /// LSN of the last completed flush.
    flushed_lsn: Lsn,
    /// Greatest block awaited by any flush request.
    requested: u64,
    /// Per-Slice flush request awaiting completion: (cycle, block).
    awaiting: Vec<Option<(u64, u64)>>,
}

impl FlushState {
    pub fn new(num_slices: usize) -> Self {
        Self {
            started: 0,
            completed: 0,
            flushed_lsn: Lsn::ZERO,
            requested: 0,
            awaiting: vec![None; num_slices],
        }
    }

    pub fn in_flight(&self) -> bool {
        self.started != self.completed
    }

    /// Whether a flush request awaits the accumulating block,
    /// which implies the block is non-empty.
    pub fn is_requested(&self) -> bool {
        self.requested > self.started
    }

    /// Whether a flush of the accumulating block should start now.
    pub fn should_start(&self, block: &BlockState) -> bool {
        !self.in_flight() && (self.is_requested() || block.is_full())
    }

    /// Request a flush for a Slice, once every Append which preceded it has
    /// been accumulated. Returns the flushed LSN if it's already satisfied.
    pub fn on_request(&mut self, slice: usize, cycle: u64, block_empty: bool) -> Option<Lsn> {
        let block = self.started + !block_empty as u64;
        if block == self.completed {
            return Some(self.flushed_lsn);
        }
        self.requested = self.requested.max(block);

        assert!(
            self.awaiting[slice].replace((cycle, block)).is_none(),
            "flush requested while a prior flush is awaiting"
        );
        None
    }

    pub fn on_started(&mut self) {
        assert!(!self.in_flight());
        self.started += 1;
    }

    /// Complete the in-flight flush, yielding the (slice, cycle) of each
    /// flush request it satisfies.
    pub fn on_completed(&mut self, flushed_lsn: Lsn) -> impl Iterator<Item = (usize, u64)> + '_ {
        assert!(self.in_flight());
        self.completed += 1;
        self.flushed_lsn = flushed_lsn;

        let completed = self.completed;
        self.awaiting
            .iter_mut()
            .enumerate()
            .filter_map(move |(slice, awaiting)| match *awaiting {
                Some((cycle, block)) if block == completed => {
                    *awaiting = None;
                    Some((slice, cycle))
                }
                _ => None,
            })
    }
}

#[cfg(test)]
mod test {
    use super::*;

    fn append(binding: u16, clock: u64, flags: u32, doc: &[u8]) -> shuffle::log_request::Append {
        shuffle::log_request::Append {
            binding: binding as u32,
            clock,
            flags,
            packed_key: bytes::Bytes::from_static(b"k"),
            doc_archived: bytes::Bytes::copy_from_slice(doc),
            ..Default::default()
        }
    }

    #[test]
    fn test_block_lifecycle() {
        let prod_1 = uuid::Producer([0, 0, 0, 0, 0, 1]);
        let prod_2 = uuid::Producer([0, 0, 0, 0, 0, 2]);
        let mut block = BlockState::new();
        assert!(block.is_empty());
        assert!(!block.is_full());

        fn last_meta(block: &BlockState) -> &BlockMeta {
            &block.entries.last().unwrap().0
        }

        // First append assigns BIDs 0/0; same journal+producer reuses them.
        block.accumulate(
            "journals/alpha",
            prod_1,
            &append(0, 100, 0x8000, b"doc_a_content"),
        );
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid,
                last_meta(&block).flags
            ),
            (0, 0, 0x8000)
        );

        block.accumulate("journals/alpha", prod_1, &append(1, 200, 0, b"doc_b"));
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid,
                last_meta(&block).flags
            ),
            (0, 0, 0)
        );

        // New journal + producer get new BIDs.
        block.accumulate(
            "journals/beta",
            prod_2,
            &append(0, 100, 0x8000, b"doc_a_content"),
        );
        assert_eq!(
            (
                last_meta(&block).journal_bid,
                last_meta(&block).producer_bid
            ),
            (1, 1)
        );

        assert!(!block.is_empty());
        insta::assert_debug_snapshot!(
            &block
                .entries
                .iter()
                .map(|(m, _, _, _)| m)
                .collect::<Vec<_>>()
        );

        // take() returns accumulated state and resets.
        let (journals, producers, entries) = block.take();
        assert_eq!((journals.len(), producers.len(), entries.len()), (2, 2, 3));
        assert!(block.is_empty());
        assert!(!block.is_full());

        // Byte threshold triggers is_full.
        block.accumulate(
            "j/a",
            prod_1,
            &append(0, 1, 0x8000, &vec![0u8; BLOCK_BYTES_THRESHOLD - 1]),
        );
        assert!(!block.is_full());
        block.accumulate("j/a", prod_1, &append(0, 2, 0x8000, b"x"));
        assert!(block.is_full());

        // Entry and BID-space exhaustion also triggers is_full.
        let mut block = BlockState::new();
        for i in 0..(1 << 16) {
            block.accumulate(&format!("j/{i}"), prod_1, &append(0, 1, 0x8000, b"x"));
        }
        assert!(block.is_full());
    }

    #[test]
    fn test_flush_state_machine() {
        let mut flush = FlushState::new(6);
        let mut block = BlockState::new();
        let prod = uuid::Producer([0, 0, 0, 0, 0, 1]);

        // Each step records its result, and the FlushState which follows it.
        let mut trace = Vec::new();
        let mut step =
            |step: &str, result: &dyn std::fmt::Debug, flush: &FlushState, block: &BlockState| {
                trace.push(format!(
                    "{step} -> {result:?}\n    should_start: {}, {flush:?}",
                    flush.should_start(block)
                ))
            };

        // Not in flight + empty block: immediately satisfied.
        step(
            "on_request(0, 1, empty)",
            &flush.on_request(0, 1, true),
            &flush,
            &block,
        );

        // Not in flight + non-empty block: awaits block 1, which should start.
        step(
            "on_request(1, 1, non-empty)",
            &flush.on_request(1, 1, false),
            &flush,
            &block,
        );
        step(
            "on_request(2, 1, non-empty)",
            &flush.on_request(2, 1, false),
            &flush,
            &block,
        );
        step("on_started", &flush.on_started(), &flush, &block);

        // In flight + empty block: awaits in-flight block 1.
        step(
            "on_request(3, 1, empty)",
            &flush.on_request(3, 1, true),
            &flush,
            &block,
        );
        // In flight + non-empty block: awaits accumulating block 2.
        step(
            "on_request(4, 2, non-empty)",
            &flush.on_request(4, 2, false),
            &flush,
            &block,
        );
        step(
            "on_request(5, 2, non-empty)",
            &flush.on_request(5, 2, false),
            &flush,
            &block,
        );

        // A full block doesn't start while a flush is in flight.
        block.accumulate(
            "j/a",
            prod,
            &append(0, 1, 0x8000, &vec![0u8; BLOCK_BYTES_THRESHOLD]),
        );
        step("accumulate(full)", &block.is_full(), &flush, &block);

        // Completion of block 1 satisfies its awaiting Slices, and block 2 should start.
        let satisfied: Vec<_> = flush.on_completed(Lsn::new(1, 0)).collect();
        step("on_completed(1/0)", &satisfied, &flush, &block);
        step("on_started", &flush.on_started(), &flush, &block);

        // Completion of block 2. A full block alone should start a flush.
        let satisfied: Vec<_> = flush.on_completed(Lsn::new(1, 1)).collect();
        step("on_completed(1/1)", &satisfied, &flush, &block);
        _ = block.take();
        step("take", &block.is_empty(), &flush, &block);

        // Satisfied immediately with the last completed LSN.
        step(
            "on_request(0, 2, empty)",
            &flush.on_request(0, 2, true),
            &flush,
            &block,
        );

        insta::assert_snapshot!(trace.join("\n"));
    }
}
