[application]
host = "127.0.0.1"
port = 3000

[application.cors]
allowed_origins = ["*"]

[database]
# database settings are canonically stored in .env files or injected into the
# environment by k8s.
