[package]
name = "librocks-exp"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
librocksdb-sys = { version = "*", default-features = false, features = ["snappy", "rtti"] }
