[package]
name = "python-connector"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
doc = { path = "../doc" }
json = { path = "../json" }

lazy_static = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }

[dev-dependencies]
sources = { path = "../sources" }
tables = { path = "../tables" }

insta = { workspace = true }
