// This file is @generated by prost-build.
/// Generated client implementations.
#[cfg(feature = "consumer_client")]
pub mod shard_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// Shard is the Consumer service API for interacting with Shards. Applications
    /// are able to wrap or alter the behavior of Shard API implementations via the
    /// Service.ShardAPI structure. They're also able to implement additional gRPC
    /// service APIs which are registered against the common gRPC server.
    #[derive(Debug, Clone)]
    pub struct ShardClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl ShardClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> ShardClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> ShardClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            ShardClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// Stat returns detailed status of a given Shard.
        pub async fn stat(
            &mut self,
            request: impl tonic::IntoRequest<::proto_gazette::consumer::StatRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::StatResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/consumer.Shard/Stat");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("consumer.Shard", "Stat"));
            self.inner.unary(req, path, codec).await
        }
        /// List Shards, their ShardSpecs and their processing status.
        pub async fn list(
            &mut self,
            request: impl tonic::IntoRequest<::proto_gazette::consumer::ListRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::ListResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/consumer.Shard/List");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("consumer.Shard", "List"));
            self.inner.unary(req, path, codec).await
        }
        /// Apply changes to the collection of Shards managed by the consumer.
        pub async fn apply(
            &mut self,
            request: impl tonic::IntoRequest<::proto_gazette::consumer::ApplyRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::ApplyResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/consumer.Shard/Apply");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("consumer.Shard", "Apply"));
            self.inner.unary(req, path, codec).await
        }
        /// GetHints fetches hints for a shard.
        pub async fn get_hints(
            &mut self,
            request: impl tonic::IntoRequest<::proto_gazette::consumer::GetHintsRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::GetHintsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/consumer.Shard/GetHints");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("consumer.Shard", "GetHints"));
            self.inner.unary(req, path, codec).await
        }
        /// Unassign a Shard.
        pub async fn unassign(
            &mut self,
            request: impl tonic::IntoRequest<::proto_gazette::consumer::UnassignRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::UnassignResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static("/consumer.Shard/Unassign");
            let mut req = request.into_request();
            req.extensions_mut().insert(GrpcMethod::new("consumer.Shard", "Unassign"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
#[cfg(feature = "consumer_server")]
pub mod shard_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with ShardServer.
    #[async_trait]
    pub trait Shard: std::marker::Send + std::marker::Sync + 'static {
        /// Stat returns detailed status of a given Shard.
        async fn stat(
            &self,
            request: tonic::Request<::proto_gazette::consumer::StatRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::StatResponse>,
            tonic::Status,
        >;
        /// List Shards, their ShardSpecs and their processing status.
        async fn list(
            &self,
            request: tonic::Request<::proto_gazette::consumer::ListRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::ListResponse>,
            tonic::Status,
        >;
        /// Apply changes to the collection of Shards managed by the consumer.
        async fn apply(
            &self,
            request: tonic::Request<::proto_gazette::consumer::ApplyRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::ApplyResponse>,
            tonic::Status,
        >;
        /// GetHints fetches hints for a shard.
        async fn get_hints(
            &self,
            request: tonic::Request<::proto_gazette::consumer::GetHintsRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::GetHintsResponse>,
            tonic::Status,
        >;
        /// Unassign a Shard.
        async fn unassign(
            &self,
            request: tonic::Request<::proto_gazette::consumer::UnassignRequest>,
        ) -> std::result::Result<
            tonic::Response<::proto_gazette::consumer::UnassignResponse>,
            tonic::Status,
        >;
    }
    /// Shard is the Consumer service API for interacting with Shards. Applications
    /// are able to wrap or alter the behavior of Shard API implementations via the
    /// Service.ShardAPI structure. They're also able to implement additional gRPC
    /// service APIs which are registered against the common gRPC server.
    #[derive(Debug)]
    pub struct ShardServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> ShardServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for ShardServer<T>
    where
        T: Shard,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/consumer.Shard/Stat" => {
                    #[allow(non_camel_case_types)]
                    struct StatSvc<T: Shard>(pub Arc<T>);
                    impl<
                        T: Shard,
                    > tonic::server::UnaryService<::proto_gazette::consumer::StatRequest>
                    for StatSvc<T> {
                        type Response = ::proto_gazette::consumer::StatResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                ::proto_gazette::consumer::StatRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Shard>::stat(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StatSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/consumer.Shard/List" => {
                    #[allow(non_camel_case_types)]
                    struct ListSvc<T: Shard>(pub Arc<T>);
                    impl<
                        T: Shard,
                    > tonic::server::UnaryService<::proto_gazette::consumer::ListRequest>
                    for ListSvc<T> {
                        type Response = ::proto_gazette::consumer::ListResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                ::proto_gazette::consumer::ListRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Shard>::list(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/consumer.Shard/Apply" => {
                    #[allow(non_camel_case_types)]
                    struct ApplySvc<T: Shard>(pub Arc<T>);
                    impl<
                        T: Shard,
                    > tonic::server::UnaryService<
                        ::proto_gazette::consumer::ApplyRequest,
                    > for ApplySvc<T> {
                        type Response = ::proto_gazette::consumer::ApplyResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                ::proto_gazette::consumer::ApplyRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Shard>::apply(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ApplySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/consumer.Shard/GetHints" => {
                    #[allow(non_camel_case_types)]
                    struct GetHintsSvc<T: Shard>(pub Arc<T>);
                    impl<
                        T: Shard,
                    > tonic::server::UnaryService<
                        ::proto_gazette::consumer::GetHintsRequest,
                    > for GetHintsSvc<T> {
                        type Response = ::proto_gazette::consumer::GetHintsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                ::proto_gazette::consumer::GetHintsRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Shard>::get_hints(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetHintsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/consumer.Shard/Unassign" => {
                    #[allow(non_camel_case_types)]
                    struct UnassignSvc<T: Shard>(pub Arc<T>);
                    impl<
                        T: Shard,
                    > tonic::server::UnaryService<
                        ::proto_gazette::consumer::UnassignRequest,
                    > for UnassignSvc<T> {
                        type Response = ::proto_gazette::consumer::UnassignResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                ::proto_gazette::consumer::UnassignRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Shard>::unassign(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnassignSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for ShardServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "consumer.Shard";
    impl<T> tonic::server::NamedService for ShardServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
