pub mod alerts;
pub(crate) mod connector_tags;
pub mod controllers;
pub(crate) mod controlplane;
mod directives;
mod discovers;
pub mod publications;
pub mod tenant_controller;

#[cfg(test)]
pub(crate) mod integration_tests;

pub use connector_tags::TagExecutor;
pub use control_plane_api::connectors::{ConnectorFactory, ControlPlaneConnectorFactory};
pub use controlplane::{ControlPlane, PGControlPlane};
pub use directives::DirectiveHandler;
pub use discovers::DiscoverExecutor;
use lazy_static::lazy_static;
pub use models::{CatalogType, Id};
use regex::Regex;

lazy_static! {
    static ref NAME_VERSION_RE: Regex = Regex::new(r#".*[_-][vV](\d+)$"#).unwrap();
}

/// Generally we use a random shard with our id generators, but there's a few
/// shards that are reserved for global processes. This module records which
/// shards are reseved for what.
pub mod id_generator {
    pub fn tenant_alerts() -> models::IdGenerator {
        models::IdGenerator::new(1)
    }
    pub fn with_random_shard() -> models::IdGenerator {
        use rand::Rng;
        // Start at 3, since 0-2 are reseved (0 is for ids generated by the database)
        let id_gen_shard = rand::rng().random_range(3u16..1024u16);
        models::IdGenerator::new(id_gen_shard)
    }
}

// timeout is a convenience for tokio::time::timeout which merges
// its error with the Future's nested anyhow::Result Output.
async fn timeout<Ok, Fut, C, WC>(
    dur: std::time::Duration,
    fut: Fut,
    with_context: WC,
) -> anyhow::Result<Ok>
where
    C: std::fmt::Display + Send + Sync + 'static,
    Fut: std::future::Future<Output = anyhow::Result<Ok>>,
    WC: FnOnce() -> C,
{
    use anyhow::Context;

    match tokio::time::timeout(dur, fut).await {
        Ok(result) => result,
        Err(err) => Err(anyhow::anyhow!(err)).with_context(with_context),
    }
}
