[package]
name = "derive-python"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "derive-python"
path = "src/main.rs"

[dependencies]
doc = { path = "../doc" }
json = { path = "../json" }
proto-flow = { path = "../proto-flow" }

anyhow = { workspace = true }
itertools = { workspace = true }
lazy_static = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[dev-dependencies]
models = { path = "../models" }
sources = { path = "../sources" }
tables = { path = "../tables" }

bytes = { workspace = true }
insta = { workspace = true }
