$defs:
  aisVessel:
    description: "a record describing the location of a vessel at a time."
    type: object
    properties:
      mmsi:
        description: "maritime mobile service identities."
        type: string
      timestamp:
        description: "the time at which the location data is reported."
        type: string
        pattern: "\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}"
      lat:
        type: number
        minimum: -90
        maximum: 90
      lon:
        type: number
        minimum: -180
        maximum: 180
      heading:
        description: "the compass direction in which the craft's bow or nose is pointed."
        type: number
      velocity:
        type: object
        properties:
          cog:
            description: "course over ground."
            type: number
          sog:
            description: "speed over ground."
            type: number
      basic:
        type: object
        properties:
          imo:
            description: "international maritime organization id"
            type: ["null", string]
          length:
            type: ["null", number]
          draft:
            type: ["null", number]
          name:
            type: ["null", string]
          status:
            type: ["null", string]
          type:
            type: ["null", string]
          width:
            type: ["null", number]
    required: [mmsi, timestamp, lat, lon]

  vesselMovement:
    description: "a record describing the movement of a vessel into or out of a H3 hexagon region."
    type: object
    properties:
      h3_index:
        description: "the id of the h3 hexagon affected. https://eng.uber.com/h3/"
        type: string
      vessel:
        description: "the ais report that triggers this movement action."
        $ref: "#/$defs/aisVessel"
      action:
        description: "the state change observed during the vessel movement.
          enter - if the vessel sails into the region.
          leave - the reverse of enter.
          closeTo - if a vessel sails into the hexagon region or its neighboring-hexagons.
                    the relationship is useful when searching for vessels that are close to each other.
                    B/c two close vessels could be located in two adjacent hexagons.
          distantFrom - the reverse of closeTo"

        type: string
        enum: [enter, leave, closeTo, distantFrom]
    required: [h3_index, vessel, action]

  vesselMovementRegister:
    description: "the type of data in the register when generating vessel movement actions. It records the id of the hexagon region in which the vessel was last observed."
    type: object
    properties:
      h3_index:
        type: string
    required: [h3_index]

  closeVesselPair:
    description: "the pair of vessels that are observed to be close to each other"
    type: object
    properties:
      vessel_a:
        $ref: "#/$defs/aisVessel"
      vessel_b:
        $ref: "#/$defs/aisVessel"
      spatial_distance_in_meters:
        description: "the calculated spatial distance between the two vessels."
        type: integer
      time_difference_in_minutes:
        description: "the time differences of the two observations of the vessels."
        type: integer
    required: [vessel_a, vessel_b, spatial_distance_in_meters, time_difference_in_minutes]

  vesselsInRegionRegister:
    description: "the type of data in the register when generating closeVesselPair. It records all the vessels located in the hexagon regions that are `closeTo` the region under consideration."
    type: object
    reduce:
      strategy: set
      key: ["/mmsi"]
    additionalProperties:
      type: array
      items:
        $ref: "#/$defs/aisVessel"
      reduce: { strategy: merge }
