
[package]
name = "dekaf"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
allocator = { path = "../allocator" }
avro = { path = "../avro" }
doc = { path = "../doc" }
extractors = { path = "../extractors" }
flow-client = { path = "../flow-client" }
gazette = { path = "../gazette" }
json = { path = "../json" }
labels = { path = "../labels" }
models = { path = "../models" }
ops = { path = "../ops" }
proto-flow = { path = "../proto-flow" }
proto-gazette = { path = "../proto-gazette" }
simd-doc = { path = "../simd-doc" }
tuple = { path = "../tuple" }
unseal = { path = "../unseal" }
coroutines = { path = "../coroutines" }

aes-siv = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
axum-server = { workspace = true }
base64 = { workspace = true }
bumpalo = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hexdump = { workspace = true }
humantime = { workspace = true }
itertools = { workspace = true }
jsonwebtoken = { workspace = true }
kafka-protocol = { workspace = true }
lazy_static = { workspace = true }
lz4_flex = { workspace = true }
md5 = { workspace = true }
metrics = { workspace = true }
metrics-exporter-prometheus = { workspace = true }
percent-encoding = { workspace = true }
postgrest = { workspace = true }
prometheus = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
rsasl = { workspace = true }
rustls = { workspace = true }
rustls-native-certs = { workspace = true }
rustls-pemfile = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-rustls = { workspace = true }
tokio-util = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing-record-hierarchical = { workspace = true }
aws-config = { workspace = true }
aws-types = { workspace = true }
aws-credential-types = { workspace = true }
aws-msk-iam-sasl-signer = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }
webpki = { workspace = true }
apache-avro = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
async-process = { path = "../async-process" }
build = { path = "../build" }
tables = { path = "../tables" }
flowctl = { path = "../flowctl" }
locate-bin = { path = "../locate-bin" }

apache-avro = { workspace = true }
insta = { workspace = true }
rdkafka = { workspace = true }
schema_registry_converter = { workspace = true }
tempfile = { workspace = true }
tracing-test = { workspace = true }
