
[package]
name = "dekaf"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
avro = { path = "../avro" }
doc = { path = "../doc" }
gazette = { path = "../gazette" }
labels = { path = "../labels" }
ops = { path = "../ops" }
flowctl = { path = "../flowctl" }
proto-flow = { path = "../proto-flow" }
proto-gazette = { path = "../proto-gazette" }
simd-doc = { path = "../simd-doc" }

anyhow = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
base64 = { workspace = true }
bytes = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
kafka-protocol = { workspace = true }
md5 = { workspace = true }
postgrest = { workspace = true }
rsasl = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
socket2 = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tokio-rustls = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
typestate = { workspace = true }
url = { workspace = true }
rustls-native-certs = { workspace = true }
deadpool = { workspace = true }
regex = { workspace = true }
hex = { workspace = true }
crypto-common = { workspace = true }
aes-siv = { workspace = true }
percent-encoding = { workspace = true }
rustls = { workspace = true }
metrics = { workspace = true }
metrics-prometheus = { workspace = true }
prometheus = { workspace = true }
hexdump = { workspace = true }
