[package]
name = "locate-bin"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
which = "4.4.0"
anyhow = { workspace = true }
tracing = { workspace = true }
