[package]
name = "protocol"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2018"

[dependencies]
anyhow = "*"
bytes = "*"
humantime-serde = "*"
prost = "*"
prost-types = "*"
serde = "*"
tracing = "*"

[dev-dependencies]
insta = "*"
serde_json = "*"

[build-dependencies]
prost-build = "*"

[features]
default = []
# The test-support feature enables additional functionality for use during tests. This feature is
# intended to only be used from "dev-dependencies"
test-support = []
