use super::producer::ProducerState;
use crate::ProducerMap;
use crate::binding::PartitionFilter;
use crate::log;
use anyhow::Context;
use proto_flow::shuffle;
use proto_gazette::uuid;

/// Immutable slice configuration: topology, bindings, and lazily-initialized
/// journal clients. Set once during Slice startup and never modified.
#[allow(dead_code)]
pub struct Topology {
    /// Unique identifier for this session, generated by the Session actor.
    /// Used as a tracing correlation value for distributed RPCs/logs.
    pub session_id: u32,
    /// Ordered shard topology: each shard owns a disjoint key range.
    pub shards: Vec<shuffle::Shard>,
    /// Index of this Slice RPC within `shards`.
    pub slice_shard_index: u32,
    /// Per-binding shuffle configuration extracted from the task spec.
    pub bindings: Vec<crate::Binding>,
    /// Lazily-initialized Gazette clients for listing and reading journals, indexed by binding.
    pub journal_clients: Vec<super::LazyJournalClient>,
    /// Sorted index for projecting hinted journal names to bindings.
    pub hint_index: HintIndex,
}

/// Flush cycle state machine, tracking in-flight flushes to Log shards.
///
/// The caller is responsible for building the frontier (from reads + causal hints)
/// and passing it to `start`. When a cycle completes, `on_flushed` returns the
/// completed frontier for the caller to reduce into accumulated progress.
///
/// Flush and progress reporting (see `ProgressState`) are deliberately decoupled
/// for latency pipelining: Slices flush autonomously after each commit without
/// waiting for a Session progress request. Multiple flush cycles can complete
/// while the Session processes the previous progress delta. When the Session sends
/// a Progress request, the accumulated flushed frontiers are often already
/// available, reducing end-to-end latency from flush_time + round_trip to
/// approximately max(flush_time, round_trip).
pub struct FlushState {
    /// Monotonically increasing flush cycle number.
    pub cycle: u64,
    /// Whether a commit has been observed since the last flush cycle started.
    ready: bool,
    /// Per-shard in-flight tracking. Non-empty while a cycle is active.
    in_flight: Vec<bool>,
    /// The frontier being flushed in the current cycle.
    flushing: crate::Frontier,
}

impl FlushState {
    pub fn new() -> Self {
        Self {
            cycle: 1,
            ready: false,
            in_flight: Vec::new(),
            flushing: Default::default(),
        }
    }

    /// Whether we're ready to begin a Flush cycle.
    pub fn should_flush(&self) -> bool {
        self.ready && self.in_flight.is_empty()
    }

    /// Record that a commit has been observed (ACK_TXN or OUTSIDE_TXN).
    pub fn set_ready(&mut self) {
        self.ready = true;
    }

    /// Begin a flush cycle with the given pre-built frontier.
    /// Returns the flush cycle number.
    pub fn start(&mut self, shard_count: usize, frontier: crate::Frontier) -> u64 {
        assert!(
            self.in_flight.is_empty(),
            "cannot start flush while one is in-flight"
        );

        self.ready = false;
        self.in_flight.resize(shard_count, true);
        self.flushing = frontier;
        self.cycle
    }

    /// Record a Flushed response from a log shard.
    /// Returns the completed frontier (with per-shard flushed LSNs) when all
    /// shards have flushed.
    pub fn on_flushed(
        &mut self,
        shard_index: usize,
        flushed_lsn: log::Lsn,
    ) -> anyhow::Result<Option<crate::Frontier>> {
        let in_flight = match self.in_flight.get_mut(shard_index) {
            Some(in_flight) if *in_flight => in_flight,
            actual => anyhow::bail!(
                "received Flushed from shard {shard_index} for cycle {} which is not in-flight (actual: {actual:?})",
                self.cycle
            ),
        };

        *in_flight = false;
        let n_pending = self.in_flight.iter().filter(|pending| **pending).count();
        self.flushing.flushed_lsn[shard_index] = flushed_lsn;

        service_kit::event!(
            tracing::Level::DEBUG,
            "log",
            shard_index,
            cycle = self.cycle,
            flushed_lsn = flushed_lsn.as_u64(),
            n_pending,
            "received Flushed response",
        );

        if n_pending != 0 {
            return Ok(None);
        }

        // We increment `cycle` now to ensure we'll clearly reject a duplicate
        // Flushed from a Log (which would be a protocol violation).
        self.in_flight.clear();
        self.cycle += 1;

        Ok(Some(std::mem::take(&mut self.flushing)))
    }
}

/// Progress reporting state, tracking the Session's outstanding progress
/// request and accumulating flushed frontiers until the request is fulfilled.
pub struct ProgressState {
    /// Whether the Session has an outstanding progress request.
    requested: bool,
    /// Accumulated frontier from completed flush cycles, awaiting reporting.
    flushed: crate::Frontier,
}

impl ProgressState {
    pub fn new() -> Self {
        Self {
            requested: false,
            flushed: Default::default(),
        }
    }

    /// Record a Progress request from the Session.
    pub fn request(&mut self) -> anyhow::Result<()> {
        if self.requested {
            anyhow::bail!("received Progress request while one is already pending");
        }
        self.requested = true;
        Ok(())
    }

    /// Reduce a completed flush frontier into accumulated progress.
    pub fn on_flush_completed(&mut self, frontier: crate::Frontier) {
        let (journals, journal_producers, bytes_read_delta, bytes_behind_delta) =
            frontier.measures();

        service_kit::event!(
            tracing::Level::DEBUG,
            "log",
            bytes_behind_delta,
            bytes_read_delta,
            journal_producers,
            journals,
            "gathered Flushed responses",
        );

        self.flushed = std::mem::take(&mut self.flushed).reduce(frontier);
    }

    /// Is progress ready to report? True iff a request is outstanding AND
    /// we've accumulated flushed progress. Idempotent — gate `take_progressed()`
    /// on this so a failed permit reservation can be retried.
    pub fn has_progressed(&self) -> bool {
        self.requested && !self.flushed.journals.is_empty()
    }

    /// Unconditionally clear the outstanding request and accumulated flushed
    /// progress, returning the latter. Callers should gate on `has_progressed()`.
    pub fn take_progressed(&mut self) -> crate::Frontier {
        self.requested = false;
        std::mem::take(&mut self.flushed)
    }
}

impl std::fmt::Debug for FlushState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("FlushState")
            .field("cycle", &self.cycle)
            .field("ready", &self.ready)
            .field("in_flight", &self.in_flight.iter().filter(|p| **p).count())
            .finish()
    }
}

impl std::fmt::Debug for ProgressState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("ProgressState")
            .field("requested", &self.requested)
            .field("flushed", &self.flushed.journals.len())
            .finish()
    }
}

/// Result of speculatively sequencing a document.
/// State is not yet committed — the caller must update producer state
/// after successful I/O.
#[derive(Debug)]
pub struct SequencedDoc {
    /// Whether the document should be appended via Log RPCs.
    pub is_append: bool,
    /// Whether this document completed a transaction (triggers flush cycle).
    pub is_commit: bool,
    /// Whether this document triggers a replay of a gapped producer.
    pub replay: bool,
    /// Updated producer state to commit after processing this document.
    pub producer_state: ProducerState,
    /// Backfill-begin control-doc clock this document committed (zero = none).
    pub backfill_begin: uuid::Clock,
    /// Backfill-complete control-doc clock this document committed (zero = none).
    pub backfill_complete: uuid::Clock,
}

/// Gate on `adjusted_clock` relative to `now`: if the clock is in the future,
/// refresh `now` via `update_now` and re-check. Returns `Some(duration)` if
/// the clock is still ahead after the refresh, or `None` if processing can proceed.
pub fn clock_delay(
    adjusted_clock: &uuid::Clock,
    now: &mut uuid::Clock,
    update_now: impl FnOnce() -> uuid::Clock,
) -> Option<std::time::Duration> {
    if adjusted_clock <= now {
        return None;
    }
    *now = update_now();
    if adjusted_clock <= now {
        return None;
    }
    Some(
        adjusted_clock
            .to_time()
            .duration_since(now.to_time())
            .unwrap_or(std::time::Duration::ZERO),
    )
}

/// Outcome of resolving a StartRead's checkpoint into a main-read start offset
/// and recovered producer state.
#[derive(Debug)]
pub struct ResolvedCheckpoint {
    /// The offset at which the main journal read starts; the maximum
    /// offset magnitude across all producer entries.
    pub offset: i64,
    /// Recovered producer states to become the read's `settled` map.
    /// Entries with an open span beginning before `offset` are marked as gapped.
    pub producers: ProducerMap<ProducerState>,
}

/// Resolve a checkpoint into a start offset and initial ProducerStates.
pub fn resolve_checkpoint(checkpoint: Vec<shuffle::ProducerFrontier>) -> ResolvedCheckpoint {
    let mut producers = ProducerMap::<ProducerState>::with_capacity_and_hasher(
        checkpoint.len(),
        Default::default(),
    );
    // First pass: recover producer states and offset of maximum progress.
    let mut max_offset = 0i64;

    for frontier in checkpoint {
        let shuffle::ProducerFrontier {
            producer,
            last_commit,
            hinted_commit: _,
            offset,
        } = frontier;

        let producer = uuid::Producer::from_i64(producer);

        // TODO(johnny): transitional — remove once pre-floor checkpoints have
        // aged out post-release. Checkpoints written before `build_flush_frontier`
        // floored read-derived entries at OBSERVED_COMMIT_FLOOR can carry
        // `last_commit == 0` on an open span. A positive `offset` proves the
        // entry is read-derived, so re-establish the writer's floor here;
        // otherwise the second pass installs a zero (non-)sentinel and the
        // gap is silently missed.
        let last_commit = uuid::Clock::from_u64(if offset > 0 {
            last_commit.max(crate::frontier::OBSERVED_COMMIT_FLOOR)
        } else {
            last_commit
        });

        max_offset = max_offset.max(offset.abs());

        producers.insert(
            producer,
            ProducerState {
                last_commit,
                max_continue: uuid::Clock::zero(),
                offset,
            },
        );
    }

    // Second pass: mark producers with an open (+offset) span beginning
    // before `max_offset` as *gapped* (the non-zero `max_continue == last_commit`
    // sentinel; see [`ProducerState::is_gapped`]).
    //
    // A hint-only producer (always offset zero) is distinguished from an actual
    // observed producer through the latter's `last_commit` at
    // OBSERVED_COMMIT_FLOOR. A hint-only producer is never gapped (we've yet
    // to see any of its documents via journal read through `max_offset`), and
    // the distinction matters as it'd otherwise force a replay from offset zero.
    for (_producer, ps) in producers.iter_mut() {
        let is_span_at_head =
            ps.offset == 0 && ps.last_commit.as_u64() == crate::frontier::OBSERVED_COMMIT_FLOOR;

        if (ps.offset > 0 && ps.offset < max_offset) || (is_span_at_head && max_offset > 0) {
            ps.max_continue = ps.last_commit;
        }
    }

    ResolvedCheckpoint {
        offset: max_offset,
        producers,
    }
}

/// Speculatively sequence a document against current `producer_state`.
///
/// Returns a `SequencedDoc` capturing the outcome, including updated state
/// which the caller must commit after consuming the sequenced document.
pub fn sequence_producer(
    mut producer_state: ProducerState,
    journal: &str,
    truncated_at: uuid::Clock,
    binding: &crate::Binding,
    meta: &super::read::Meta,
) -> anyhow::Result<SequencedDoc> {
    let super::read::Meta {
        producer,
        clock,
        flags,
        backfill_event: marker,
        begin_offset,
        end_offset,
    } = meta;

    // Determine the message's sequencing outcome.
    let was_gapped = producer_state.is_gapped();
    let outcome = uuid::sequence(
        *flags,
        *clock,
        &mut producer_state.last_commit,
        &mut producer_state.max_continue,
    )
    .with_context(|| {
        format!(
            "failed to sequence journal {journal} (binding {}) document at offset {begin_offset} \
            (producer {producer:?} with clock {clock:?}, last_commit {:?}, max_continue {:?})",
            binding.state_key(),
            producer_state.last_commit,
            producer_state.max_continue,
        )
    })?;

    // A gapped producer's first newer CONTINUE or ACK is its replay trigger.
    // Other outcomes drop (duplicate) or durably resolve the gap.
    let replay = was_gapped
        && matches!(
            outcome,
            uuid::SequenceOutcome::ContinueExtendSpan | uuid::SequenceOutcome::AckCommit
        );

    let mut backfill_begin = uuid::Clock::zero();
    let mut backfill_complete = uuid::Clock::zero();

    // Match over `outcome` to update `producer_state` and determine append/commit.
    let (is_append, is_commit) = match outcome {
        uuid::SequenceOutcome::OutsideCommit => {
            producer_state.offset = -*end_offset;
            (true, true)
        }
        uuid::SequenceOutcome::OutsideDuplicate => (false, false),
        uuid::SequenceOutcome::ContinueBeginSpan => {
            producer_state.offset = *begin_offset;
            (true, false)
        }
        uuid::SequenceOutcome::ContinueExtendSpan => (true, false),
        uuid::SequenceOutcome::ContinueDuplicate => (false, false),
        uuid::SequenceOutcome::AckDeepRollback => {
            tracing::warn!(
                binding=%binding.state_key(),
                clock=?clock,
                %journal,
                last_commit=?producer_state.last_commit,
                producer=?producer,
                "detected rollback prior to last committed clock of the producer (possible loss of exactly-once guarantees)",
            );
            producer_state.offset = -*end_offset;
            (false, true)
        }
        uuid::SequenceOutcome::AckCommit
        | uuid::SequenceOutcome::AckEmpty
        | uuid::SequenceOutcome::AckCleanRollback => {
            // This ACK commits (or rolls back) the producer's preceding
            // CONTINUE_TXN documents in this journal only. Cross-journal
            // visibility for the same producer transaction is handled separately
            // via `extract_causal_hints`.
            //
            // A committing ACK also folds any backfill marker it carries. Markers
            // are broadcast on ACKs and delivered exactly once per committed
            // generation; a conservative re-read that replays the ACK as
            // `AckDuplicate` (or an `AckDeepRollback`) must NOT re-fold, which is
            // why the fold lives on this arm alone.
            match marker {
                Some(super::read::BackfillEvent::BackfillBegin) => backfill_begin = *clock,
                Some(super::read::BackfillEvent::BackfillComplete { truncated_at }) => {
                    backfill_complete = *truncated_at
                }
                None => {}
            }
            producer_state.offset = -*end_offset;
            (false, true)
        }
        uuid::SequenceOutcome::AckDuplicate => (false, false),
    };

    // A `notBefore`/`notAfter` window and the journal's `truncated_at`
    // truncation boundary all suppress document append, but don't impact the
    // propagation of flush and progress reporting.
    let is_append = is_append
        && *clock >= binding.not_before
        && *clock >= truncated_at
        && *clock < binding.not_after;

    tracing::trace!(
        %journal,
        binding = binding.state_key(),
        ?producer,
        ?clock,
        begin_offset,
        ?outcome,
        is_append,
        is_commit,
        replay,
        "sequenced document"
    );

    Ok(SequencedDoc {
        is_append,
        is_commit,
        replay,
        producer_state,
        backfill_begin,
        backfill_complete,
    })
}

/// Sorted index for projecting hinted journal names to (binding_index, cohort),
/// with per-entry partition filters.
///
/// Entries are sorted by prefix then binding index. Because the control plane
/// guarantees no collection is a prefix of another, at most one distinct prefix
/// can match a given journal name — so lookup is a single binary search plus
/// a linear scan of adjacent entries sharing that prefix.
///
/// Hints are filtered to the ACK's cohort because cohorts (unique (priority,
/// read_delay) tuples) have independent visibility semantics. If a producer
/// writes to journals spanning multiple read cohorts within one of its transactions,
/// we only want to gate progress on reading commits from journals matching
/// the ACK's cohort.
///
/// If we didn't filter in this way, then progress of a journal read in real-time
/// could be blocked by the read-delay applied to a hinted journal. Or similarly,
/// a high-priority journal could be blocked by a low-priority hinted journal.
///
/// Hinted journals of other cohorts will have their own ACKs, and will project to
/// hints internal to their own cohort's progress tracking.
pub struct HintIndex {
    /// (prefix, binding_index, cohort, filter), sorted by (prefix, binding_index).
    entries: Vec<(Box<str>, u16, u32, PartitionFilter)>,
    /// True if some cohort reads one journal-prefix under multiple bindings — so a
    /// journal may be read by ≥2 bindings of a cohort. When false (the common case
    /// where each journal maps 1:1 to a binding), `extract_causal_hints` skips
    /// same-cohort self-hint projection, paying only a boolean test per ACK.
    cohort_shares_journal: bool,
}

impl HintIndex {
    pub fn new<'a>(entries: impl Iterator<Item = (&'a str, u16, u32, PartitionFilter)>) -> Self {
        let mut index: Vec<(&str, u16, u32, PartitionFilter)> = entries.collect();

        index.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));

        // A cohort reads a journal under multiple bindings iff two entries share a
        // (prefix, cohort). We can't rely on the (prefix, binding) sort to make
        // such a pair adjacent: a binding of a different cohort on the same prefix
        // can sort between them. For example priorities `[0, 1, 0]` assign cohorts
        // `[0, 1, 0]`, where bindings 0 and 2 share cohort 0 but binding 1 sorts
        // between them. Detect any duplicate (prefix, cohort) regardless of order.
        // This is conservative — `lookup`'s partition filter still scopes self-hints
        // to bindings that actually read a given journal — but it cheaply clears the
        // common 1:1 case.
        let mut seen_prefix_cohort = std::collections::HashSet::new();
        let cohort_shares_journal = index
            .iter()
            .any(|(prefix, _, cohort, _)| !seen_prefix_cohort.insert((*prefix, *cohort)));

        // Now that we've sorted, re-allocate partition name prefixes.
        // This ensures aligns memory locality and ordering with our query pattern.
        let entries: Vec<(Box<str>, u16, u32, PartitionFilter)> = index
            .into_iter()
            .map(|(prefix, idx, cohort, filter)| (Box::from(prefix), idx, cohort, filter))
            .collect();

        Self {
            entries,
            cohort_shares_journal,
        }
    }

    pub fn from_bindings(bindings: &[crate::Binding]) -> Self {
        Self::new(bindings.iter().map(|b| {
            (
                b.partition_prefix.as_ref(),
                b.index,
                b.cohort,
                PartitionFilter::new(&b.partition_fields, &b.partition_selector),
            )
        }))
    }

    /// Find all binding indices whose prefix matches `journal` within `cohort`,
    /// filtering by each entry's partition selector.
    ///
    /// Because no collection prefix is a prefix of another, there is at most
    /// one matching prefix for any journal name.
    pub fn lookup(&self, journal: &str, cohort: u32, out: &mut Vec<u16>) -> anyhow::Result<()> {
        out.clear();

        // Find the first entry whose partition name prefix is > journal.
        // The matching prefix, if any, is immediately before this position.
        let pos = self
            .entries
            .partition_point(|(prefix, _, _, _)| prefix.as_ref() <= journal);
        if pos == 0 {
            return Ok(());
        }

        // Check whether the entry just before `pos` is a prefix of `journal`.
        let matched_prefix = &self.entries[pos - 1].0;
        if !journal.starts_with(matched_prefix.as_ref()) {
            return Ok(());
        }

        // Scan all entries sharing this prefix (they are contiguous and sorted).
        for &(ref prefix, binding_idx, binding_cohort, ref filter) in
            self.entries[..pos].iter().rev()
        {
            if prefix != matched_prefix {
                break;
            }
            if binding_cohort == cohort
                && filter.matches_name_suffix(&journal[matched_prefix.len()..])?
            {
                out.push(binding_idx);
            }
        }

        Ok(())
    }
}

/// Decode causal hints from an ACK document and project them through the
/// `hint_index` into `causal_hints` entries keyed by (journal, binding_index).
pub fn extract_causal_hints<N: json::AsNode>(
    hint_index: &HintIndex,
    ack_journal: &str,
    ack_cohort: u32,
    ack_binding_index: u16,
    ack_producer: uuid::Producer,
    ack_clock: uuid::Clock,
    ack_doc: &N,
    causal_hints: &mut super::CausalHints,
) -> anyhow::Result<()> {
    let mut hint_iter =
        publisher::intents::decode_transaction_hints(ack_journal, ack_producer, ack_clock, ack_doc);
    let mut matched_bindings = Vec::new();

    while let Some(result) = hint_iter.next() {
        let (hinted_journal, hinted_producer, hinted_clock) = result.map_err(|err| {
            anyhow::anyhow!("decoding causal hint from ACK in {ack_journal}: {err}")
        })?;

        hint_index.lookup(hinted_journal, ack_cohort, &mut matched_bindings)?;

        for &binding_idx in &matched_bindings {
            causal_hints
                .entry((hinted_journal.into(), binding_idx))
                .or_default()
                .push((hinted_producer, hinted_clock));
        }
    }

    // An ACK doc carries hints only for *other* journals, but one journal may
    // be read by multiple bindings of a cohort. Project a self-hint from this
    // ACK's own (journal, producer) to the *other* cohort bindings reading the
    // journal, so checkpoint visibility is held until all have read through the
    // producer's commit. Skipped unless a cohort actually shares a journal
    // across bindings.
    if hint_index.cohort_shares_journal {
        hint_index.lookup(ack_journal, ack_cohort, &mut matched_bindings)?;

        for &binding_idx in &matched_bindings {
            if binding_idx == ack_binding_index {
                continue;
            }
            causal_hints
                .entry((ack_journal.into(), binding_idx))
                .or_default()
                .push((ack_producer, ack_clock));
        }
    }

    Ok(())
}

#[cfg(test)]
mod test {
    use super::super::CausalHints;
    use super::super::read::{Meta, ReadState};
    use super::*;
    use crate::testing::test_binding;
    use proto_gazette::broker;
    use proto_gazette::uuid::{Clock, Flags, Producer};

    const OUTSIDE: Flags = Flags(proto_gazette::message_flags::OUTSIDE_TXN as u16);
    const CONTINUE: Flags = Flags(proto_gazette::message_flags::CONTINUE_TXN as u16);
    const ACK: Flags = Flags(proto_gazette::message_flags::ACK_TXN as u16);

    fn meta(
        producer: Producer,
        clock: Clock,
        flags: Flags,
        begin_offset: i64,
        end_offset: i64,
    ) -> Meta {
        Meta {
            producer,
            clock,
            flags,
            begin_offset,
            end_offset,
            backfill_event: None,
        }
    }

    fn producer(id: u8) -> Producer {
        Producer::from_bytes([id | 0x01, 0, 0, 0, 0, 0])
    }

    /// Test helper mirroring the drain loop's hot path: one pending-else-settled
    /// lookup, then the pure `sequence_producer` (the single sequencing path for
    /// gapped and non-gapped producers alike).
    fn sequence(
        read_state: &ReadState,
        binding: &crate::Binding,
        meta: &Meta,
    ) -> anyhow::Result<SequencedDoc> {
        let producer_state = read_state.producer_state(meta.producer);
        sequence_producer(
            producer_state,
            &read_state.journal,
            read_state.truncated_at,
            binding,
            meta,
        )
    }

    /// Build a checkpoint entry for a producer with zero clocks and a committed offset.
    /// This is the minimal "known producer" state needed by tests.
    fn checkpoint_entry(p: &Producer, committed_end: i64) -> shuffle::ProducerFrontier {
        shuffle::ProducerFrontier {
            producer: p.as_i64(),
            last_commit: 0,
            hinted_commit: 0,
            offset: -committed_end, // Negative = committed end offset.
        }
    }

    struct TestState {
        bindings: Vec<crate::Binding>,
        reads: Vec<ReadState>,
        flush: FlushState,
        progress: ProgressState,
    }

    fn test_state(bindings: Vec<crate::Binding>) -> TestState {
        TestState {
            bindings,
            reads: Vec::new(),
            flush: FlushState::new(),
            progress: ProgressState::new(),
        }
    }

    impl TestState {
        fn commit(&mut self, read_id: usize, producer: Producer, seq: SequencedDoc) {
            let read = &mut self.reads[read_id];
            read.backfill_begin = read.backfill_begin.max(seq.backfill_begin);
            read.backfill_complete = read.backfill_complete.max(seq.backfill_complete);
            _ = read.pending.insert(producer, seq.producer_state);
            if seq.is_commit {
                self.flush.set_ready();
            }
        }
    }

    fn cp(p: &Producer, offset: i64) -> shuffle::ProducerFrontier {
        cp_lc(p, 100, offset)
    }

    /// Checkpoint entry with an explicit raw `last_commit`, for the floor (raw 1,
    /// a span at journal head) and hint-only (raw 0) cases where the encoding
    /// matters.
    fn cp_lc(p: &Producer, last_commit: u64, offset: i64) -> shuffle::ProducerFrontier {
        shuffle::ProducerFrontier {
            producer: p.as_i64(),
            last_commit,
            hinted_commit: 0,
            offset,
        }
    }

    /// Sorted (offset, gapped) tuple per producer, for stable assertions. While
    /// gapped the offset is the pinned begin `F`.
    fn gap_summary(r: &ResolvedCheckpoint) -> Vec<(i64, bool)> {
        let mut out: Vec<(i64, bool)> = r
            .producers
            .iter()
            .map(|(_p, ps)| (ps.offset, ps.is_gapped()))
            .collect();
        out.sort();
        out
    }

    /// True if no recovered producer is gapped.
    fn no_gaps(r: &ResolvedCheckpoint) -> bool {
        r.producers.iter().all(|(_p, ps)| !ps.is_gapped())
    }

    #[test]
    fn test_resolve_checkpoint() {
        let p1 = producer(0x01);
        let p3 = producer(0x03);
        let p5 = producer(0x05);

        // Empty checkpoint → M = 0, no gaps.
        let r = resolve_checkpoint(vec![]);
        assert_eq!(r.offset, 0);
        assert!(r.producers.is_empty() && no_gaps(&r));

        // All committed: M = max magnitude, no gaps.
        let r = resolve_checkpoint(vec![cp(&p1, -500), cp(&p3, -1000)]);
        assert_eq!(r.offset, 1000);
        assert!(no_gaps(&r));

        // Mixed: M = 1000 (max magnitude, from the committed -1000); both
        // uncommitted spans (300, 100) begin before M → gapped.
        let r = resolve_checkpoint(vec![cp(&p1, -1000), cp(&p3, 300), cp(&p5, 100)]);
        assert_eq!(r.offset, 1000);
        assert_eq!(
            gap_summary(&r),
            vec![(-1000, false), (100, true), (300, true)]
        );

        // An uncommitted span at exactly M is recovered normally: the main
        // read encounters it from its first document.
        let r = resolve_checkpoint(vec![cp(&p1, -300), cp(&p3, 300), cp(&p5, 100)]);
        assert_eq!(r.offset, 300);
        assert_eq!(
            gap_summary(&r),
            vec![(-300, false), (100, true), (300, false)]
        );

        // offset == 0 with a real last_commit (a hint-elevated `{C > 1, 0}`) is
        // NOT gapped: the commit is already durably delivered, and resuming from
        // M skips nothing.
        let r = resolve_checkpoint(vec![cp(&p1, 0), cp(&p3, 500)]);
        assert_eq!(r.offset, 500);
        assert_eq!(gap_summary(&r), vec![(0, false), (500, false)]);

        // A hint-only placeholder `{0, 0}` is NOT gapped: a hint-only producer
        // proves all of its documents lie above M.
        let r = resolve_checkpoint(vec![cp_lc(&p1, 0, 0), cp(&p3, -500)]);
        assert_eq!(r.offset, 500);
        assert_eq!(gap_summary(&r), vec![(-500, false), (0, false)]);

        // The floor `{raw 1, 0}` is a real span at F = 0: gapped when M > 0. The
        // floored `last_commit` recovers as-is (raw 1), NOT normalized to zero.
        let r = resolve_checkpoint(vec![cp_lc(&p1, 1, 0), cp(&p3, -500)]);
        assert_eq!(r.offset, 500);
        assert_eq!(gap_summary(&r), vec![(-500, false), (0, true)]);
        assert_eq!(
            r.producers.get(&p1).unwrap().last_commit,
            Clock::from_u64(1),
            "the floored last_commit recovers as raw 1, not normalized",
        );

        // Transitional: a pre-floor checkpoint entry `{raw 0, +F}` (persisted
        // before `build_flush_frontier` floored read-derived entries) has its
        // floor re-established at read time, and recovers gapped exactly as a
        // floor-era checkpoint would.
        let r = resolve_checkpoint(vec![cp_lc(&p1, 0, 300), cp(&p3, -500)]);
        assert_eq!(r.offset, 500);
        assert_eq!(gap_summary(&r), vec![(-500, false), (300, true)]);
        assert_eq!(
            r.producers.get(&p1).unwrap().last_commit,
            Clock::from_u64(1),
            "the read-time floor recovers as raw 1, matching the writer's floor",
        );

        // Floor with M == 0: not gapped — the sole span begins at journal
        // start and the main read covers it — and still recovers as raw 1.
        let r = resolve_checkpoint(vec![cp_lc(&p1, 1, 0)]);
        assert_eq!(r.offset, 0);
        assert!(no_gaps(&r));
        assert_eq!(
            r.producers.get(&p1).unwrap().last_commit,
            Clock::from_u64(1),
        );

        // offset == 0 with M == 0 recovers un-gapped regardless of last_commit.
        let r = resolve_checkpoint(vec![cp(&p1, 0)]);
        assert_eq!(r.offset, 0);
        assert!(no_gaps(&r));
    }

    #[test]
    fn test_hint_only_recovery_sequences_organically() {
        // A recovered hint-only producer `{0, H, 0}` with M > 0 is NOT gapped,
        // and its later commit at-or-above M sequences through the wholly
        // ordinary path — no replay trigger fires.
        let binding = test_binding(0, true, None, "/suffix");
        let p1 = producer(0x01);
        let p3 = producer(0x03);

        let r = resolve_checkpoint(vec![cp_lc(&p1, 0, 0), cp(&p3, -500)]);
        let state = *r.producers.get(&p1).unwrap();
        assert!(!state.is_gapped());

        // Its OUTSIDE commit above M commits organically (no replay).
        let s = sequence_producer(
            state,
            "test/journal",
            Clock::zero(),
            &binding,
            &meta(p1, Clock::from_u64(150), OUTSIDE, 500, 600),
        )
        .unwrap();
        assert!(s.is_commit && !s.replay);
        assert_eq!(s.producer_state.offset, -600);

        // And so does a CONTINUE + ACK transaction above M. (`is_append` is not
        // asserted: this table's raw clocks sit below the binding's `not_before`
        // floor, which suppresses appends orthogonally to sequencing.)
        let s = sequence_producer(
            state,
            "test/journal",
            Clock::zero(),
            &binding,
            &meta(p1, Clock::from_u64(150), CONTINUE, 500, 600),
        )
        .unwrap();
        assert!(!s.is_commit && !s.replay);
        assert_eq!(s.producer_state.offset, 500, "span begins at F = 500 >= M");
        let s = sequence_producer(
            s.producer_state,
            "test/journal",
            Clock::zero(),
            &binding,
            &meta(p1, Clock::from_u64(150), ACK, 600, 700),
        )
        .unwrap();
        assert!(s.is_commit && !s.replay);
        assert_eq!(s.producer_state.offset, -700);
    }

    #[test]
    fn test_sequence_gapped_producer_table() {
        // Drive the full main-read outcome table for a gapped producer through the
        // single `sequence_producer` path: every disposition a gapped span can reach
        // from a newer document — CONTINUE/ACK replay triggers, duplicate drops,
        // clean and deep rollbacks, and the OUTSIDE protocol violation. The gapped
        // state is `last_commit = L = 100` with the non-zero `max_continue == L`
        // sentinel that `resolve_checkpoint` installs on recovery, frozen at `F = 40`.
        let binding = test_binding(0, true, None, "/suffix");
        let journal = "test/journal";
        let p = producer(0x01);

        let gapped = ProducerState {
            last_commit: Clock::from_u64(100),
            max_continue: Clock::from_u64(100), // Gapped: max_continue == last_commit.
            offset: 40,
        };
        assert!(gapped.is_gapped(), "the sentinel marks the producer gapped");

        // `gapped` is Copy, so each call sequences against the same frozen state.
        let seq = |flags, clock| {
            sequence_producer(
                gapped,
                journal,
                Clock::zero(),
                &binding,
                &meta(p, Clock::from_u64(clock), flags, 400, 500),
            )
        };

        // A real newer CONTINUE (clock > L) extends the span → replay trigger.
        let s = seq(CONTINUE, 150).unwrap();
        assert!(s.replay, "newer CONTINUE is a replay trigger");

        // The `L + 1` boundary: a span-begin CONTINUE at exactly `last_commit + 1`
        // extends the span rather than being dropped, triggering a replay.
        let s = seq(CONTINUE, 101).unwrap();
        assert!(
            s.replay,
            "a CONTINUE at L+1 is a real span doc → replay trigger"
        );

        // A newer ACK commits the span → replay trigger.
        let s = seq(ACK, 150).unwrap();
        assert!(s.replay, "newer ACK is a replay trigger");

        // Duplicate CONTINUEs at and below `L` drop with the sentinel intact: the
        // returned state is bit-identical to the frozen input (freeze invariant).
        for clock in [100u64, 50] {
            let s = seq(CONTINUE, clock).unwrap();
            assert!(
                !s.replay && !s.is_append && !s.is_commit,
                "duplicate CONTINUE at clock {clock} is dropped",
            );
            assert_eq!(
                s.producer_state.last_commit, gapped.last_commit,
                "clock {clock}: last_commit frozen",
            );
            assert_eq!(
                s.producer_state.max_continue, gapped.max_continue,
                "clock {clock}: sentinel intact",
            );
            assert_eq!(
                s.producer_state.offset, gapped.offset,
                "clock {clock}: F frozen",
            );
            assert!(
                s.producer_state.is_gapped(),
                "clock {clock}: producer stays gapped",
            );
        }

        // ACK == L: durable clean rollback (no replay), committed at -ack_end.
        let s = seq(ACK, 100).unwrap();
        assert!(
            s.is_commit && !s.replay && !s.is_append,
            "clean rollback commits without replay",
        );
        assert_eq!(
            s.producer_state.offset, -500,
            "clean rollback yields the committed -ack_end",
        );
        assert!(
            !s.producer_state.is_gapped(),
            "clean rollback clears the gap",
        );

        // ACK < L: durable deep rollback. `last_commit` regresses to the ACK clock.
        let s = seq(ACK, 50).unwrap();
        assert!(s.is_commit && !s.replay, "deep rollback commits");
        assert_eq!(
            s.producer_state.last_commit,
            Clock::from_u64(50),
            "deep rollback regresses last_commit to the ACK clock",
        );
        assert_eq!(s.producer_state.offset, -500);
        assert!(
            !s.producer_state.is_gapped(),
            "deep rollback clears the gap",
        );

        // Any OUTSIDE against the gapped sentinel errors with
        // `OutsideWithPrecedingContinue` — identical to a non-gapped producer
        // carrying a genuine pending span. The sentinel `max_continue == L`
        // stands for a real (if unread) open span, and the producer protocol
        // forbids an OUTSIDE_TXN before that span's terminating ACK_TXN. The error
        // precedes any clock comparison, so it holds at every clock: a gapped
        // OUTSIDE is never a replay trigger and never commits, and the session
        // fail-fasts. We deliberately pin this to the span as first read — a later
        // fragment loss that erased the CONTINUE does not soften it to a commit.
        for clock in [150u64, 100, 50] {
            let err = seq(OUTSIDE, clock).unwrap_err();
            assert!(
                format!("{err:#}")
                    .contains("OUTSIDE_TXN with a preceding unacknowledged CONTINUE_TXN"),
                "gapped OUTSIDE at clock {clock} errors: {err:#}",
            );
        }
    }

    #[test]
    fn test_organic_adjacent_clocks_never_gap() {
        // Pre-microsecond-tick journal data advances Clocks by +1 raw, so a
        // producer's next-transaction CONTINUE can be stamped at exactly
        // `last_commit + 1`. Such a span must sequence as an ordinary new span,
        // never as a gapped producer — otherwise the session wedges in an endless
        // replay (the span-begin doc re-derives the old `L + 1` sentinel forever).
        // Drive the +1-adjacent boundary straight through `sequence_producer`.
        let binding = test_binding(0, true, None, "/suffix");
        let journal = "test/journal";
        let p = producer(0x01);

        // A producer committed at clock C via a prior ACK/OUTSIDE.
        let committed = ProducerState {
            last_commit: Clock::from_u64(1_000),
            max_continue: Clock::zero(),
            offset: -900, // Negative = committed end offset.
        };
        assert!(!committed.is_gapped(), "a committed producer is not gapped");

        // Its next transaction's first CONTINUE lands at exactly C + 1.
        let s = sequence_producer(
            committed,
            journal,
            Clock::zero(),
            &binding,
            &meta(p, Clock::from_u64(1_001), CONTINUE, 900, 950),
        )
        .unwrap();
        assert!(
            !s.replay,
            "an organic C+1 span-begin CONTINUE is not a replay trigger",
        );
        assert!(
            !s.producer_state.is_gapped(),
            "the C+1 span-begin must not masquerade as the gapped sentinel",
        );
        assert_eq!(s.producer_state.max_continue, Clock::from_u64(1_001));
        assert_eq!(
            s.producer_state.offset, 900,
            "span begins at its CONTINUE offset"
        );

        // A following CONTINUE at C + 2 extends the span; still no replay, and the
        // producer that would previously have looked gapped at entry does not.
        let s = sequence_producer(
            s.producer_state,
            journal,
            Clock::zero(),
            &binding,
            &meta(p, Clock::from_u64(1_002), CONTINUE, 950, 1_000),
        )
        .unwrap();
        assert!(!s.replay, "an extending CONTINUE must not trigger a replay");
        assert!(!s.producer_state.is_gapped());

        // The ACK at C + 3 commits the span organically — no replay, gap cleared.
        let s = sequence_producer(
            s.producer_state,
            journal,
            Clock::zero(),
            &binding,
            &meta(p, Clock::from_u64(1_003), ACK, 1_000, 1_050),
        )
        .unwrap();
        assert!(
            s.is_commit && !s.replay,
            "the span commits without any replay"
        );
        assert!(!s.producer_state.is_gapped());
        assert_eq!(s.producer_state.offset, -1_050);
    }

    #[test]
    fn test_gapped_rollback_is_durable() {
        // A gapped clean/deep rollback emits a committed entry (offset =
        // -ack_end). Re-resolving that checkpoint must not recreate the gap — a
        // durably-resolved rollback stays resolved across restart — even when
        // other producers raise M.
        let p = producer(0x01);
        let p2 = producer(0x03);

        let r = resolve_checkpoint(vec![cp(&p, -450)]);
        assert!(no_gaps(&r), "committed offset is never gapped");

        let r = resolve_checkpoint(vec![cp(&p, -450), cp(&p2, -100_000)]);
        assert!(
            !r.producers.get(&p).unwrap().is_gapped(),
            "rolled-back producer stays committed across restart",
        );
    }

    #[test]
    fn test_sequence_not_before_not_after() {
        let mut bindings = vec![test_binding(0, true, None, "/suffix")];
        bindings[0].not_before = Clock::from_u64(100);
        bindings[0].not_after = Clock::from_u64(500);

        let mut s = test_state(bindings);

        let p1 = producer(0x01);

        // Start read with p1 in the checkpoint.
        let producers = resolve_checkpoint(vec![checkpoint_entry(&p1, 0)]).producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            truncated_at: Clock::zero(),
            backfill_begin: Clock::zero(),
            backfill_complete: Clock::zero(),
            settled: producers,
            pending: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // Clock before notBefore: suppresses append but not commit.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(50), OUTSIDE, 0, 50),
        )
        .unwrap();
        assert!(!seq.is_append, "before notBefore → no append");
        assert!(seq.is_commit, "before notBefore → commit still propagates");
        s.commit(0, p1, seq);

        // Clock within range: normal append.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(200), OUTSIDE, 50, 100),
        )
        .unwrap();
        assert!(seq.is_append, "within range → append");
        assert!(seq.is_commit, "within range → commit");
        s.commit(0, p1, seq);

        // Clock at notAfter boundary: suppresses append (notAfter is exclusive).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_u64(500), OUTSIDE, 100, 150),
        )
        .unwrap();
        assert!(!seq.is_append, "at notAfter → no append");
        assert!(seq.is_commit, "at notAfter → commit still propagates");
    }

    #[test]
    fn test_flush_state_machine() {
        let mut s = test_state(vec![test_binding(0, true, None, "/suffix")]);

        let p1 = producer(0x01);
        let p3 = producer(0x03);

        // Start read with both producers in the checkpoint.
        let producers =
            resolve_checkpoint(vec![checkpoint_entry(&p1, 0), checkpoint_entry(&p3, 0)]).producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            truncated_at: Clock::zero(),
            backfill_begin: Clock::zero(),
            backfill_complete: Clock::zero(),
            settled: producers,
            pending: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // Initially: flush not ready → should_flush false.
        assert!(!s.flush.should_flush());

        // Sequence an OUTSIDE commit (sets flush ready via commit_enqueue).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(100, 0), OUTSIDE, 0, 50),
        )
        .unwrap();
        s.commit(0, p1, seq);

        // Now should_flush is true.
        assert!(s.flush.should_flush());

        // Add a second producer's document for richer frontier.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p3, Clock::from_unix(200, 0), OUTSIDE, 50, 100),
        )
        .unwrap();
        s.commit(0, p3, seq);

        // Build frontier and start flush with 3 shards.
        let frontier =
            super::super::producer::build_flush_frontier(&mut s.reads, std::iter::empty(), 3);
        assert!(!frontier.journals.is_empty(), "flushing frontier built");

        let flush_cycle = s.flush.start(3, frontier);
        assert_eq!(flush_cycle, 1, "flush_cycle is the current cycle");
        assert!(!s.flush.should_flush(), "not ready after start");
        assert!(s.reads[0].pending.is_empty(), "pending drained to settled");

        // Partial flushed: still in flight.
        assert!(
            s.flush
                .on_flushed(0, log::Lsn::new(0, 100))
                .unwrap()
                .is_none(),
            "still in flight after 1/3"
        );
        assert!(
            s.flush
                .on_flushed(2, log::Lsn::new(0, 300))
                .unwrap()
                .is_none(),
            "still in flight after 2/3"
        );

        // All flushed: returns completed frontier. Cycle advances so that
        // a duplicate Flushed with the old cycle is rejected as a protocol violation.
        let completed = s
            .flush
            .on_flushed(1, log::Lsn::new(0, 200))
            .unwrap()
            .expect("all flushed");

        assert_eq!(
            s.flush.cycle, 2,
            "cycle incremented after all shards flushed"
        );
        s.progress.on_flush_completed(completed);

        insta::assert_debug_snapshot!("flush_state_machine", &s.progress.flushed);
    }

    #[test]
    fn test_progress_reporting() {
        let mut progress = ProgressState::new();

        // No request + no flushed → not ready.
        assert!(!progress.has_progressed());

        // Request but no flushed → not ready.
        progress.request().unwrap();
        assert!(!progress.has_progressed());
        // requested should remain true.
        assert!(progress.requested);

        // Populate flushed directly for this test.
        progress.flushed = crate::Frontier {
            journals: vec![crate::JournalFrontier {
                journal: "test/journal/A".into(),
                binding: 0,
                producers: vec![crate::ProducerFrontier {
                    producer: producer(0x01),
                    last_commit: Clock::from_u64(100),
                    hinted_commit: Clock::from_u64(0),
                    offset: -500,
                }],
                bytes_read_delta: 0,
                bytes_behind_delta: 0,
            }],
            flushed_lsn: vec![],
            unresolved_hints: 0,
            ..Default::default()
        };

        // Request + flushed → has_progressed gates, take_progressed consumes.
        assert!(progress.has_progressed());
        let frontier = progress.take_progressed();
        assert!(!progress.requested, "requested cleared");
        assert!(progress.flushed.journals.is_empty(), "flushed cleared");
        assert_eq!(frontier.journals.len(), 1);

        // Double request is an error.
        progress.request().unwrap();
        let err = progress.request().unwrap_err();
        assert!(
            format!("{err}").contains("already pending"),
            "expected double-request error, got: {err}"
        );
    }

    #[test]
    fn test_clock_delay() {
        let mut now = Clock::from_unix(100, 0);

        // Clock in the past: no delay, update_now not called.
        let past = Clock::from_unix(50, 0);
        assert!(clock_delay(&past, &mut now, || panic!("should not refresh")).is_none());

        // Clock equal to now: no delay.
        let equal = Clock::from_unix(100, 0);
        assert!(clock_delay(&equal, &mut now, || panic!("should not refresh")).is_none());

        // Clock in the future, but refresh catches up: no delay.
        let future1 = Clock::from_unix(110, 0);
        assert!(clock_delay(&future1, &mut now, || Clock::from_unix(110, 0)).is_none());
        assert_eq!(now, Clock::from_unix(110, 0), "now was refreshed");

        // Clock in the future even after refresh: returns remaining delay.
        let future2 = Clock::from_unix(120, 0);
        let delay = clock_delay(&future2, &mut now, || Clock::from_unix(115, 0)).unwrap();
        assert_eq!(delay, std::time::Duration::from_secs(5));
        assert_eq!(now, Clock::from_unix(115, 0), "now was refreshed");
    }

    /// Tests the offset tracking and is_enqueue/is_commit disposition that
    /// sequence_producer layers on top of uuid::sequence (which has its own
    /// exhaustive tests for clock state transitions).
    #[test]
    fn test_sequence_offset_and_disposition() {
        let bindings = vec![test_binding(0, true, None, "/suffix")];
        let mut s = test_state(bindings);

        let p1 = producer(0x01);

        let producers = resolve_checkpoint(vec![checkpoint_entry(&p1, 0)]).producers;
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            truncated_at: Clock::zero(),
            backfill_begin: Clock::zero(),
            backfill_complete: Clock::zero(),
            settled: producers,
            pending: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // ContinueBeginSpan: enqueued, no commit, offset set to begin_offset.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(10, 0), CONTINUE, 100, 150),
        )
        .unwrap();
        assert!(seq.is_append);
        assert!(!seq.is_commit);
        assert_eq!(
            seq.producer_state.offset, 100,
            "offset = begin of uncommitted span"
        );
        s.commit(0, p1, seq);

        // ContinueExtendSpan: enqueued, no commit, offset preserved from BeginSpan.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), CONTINUE, 150, 200),
        )
        .unwrap();
        assert!(seq.is_append);
        assert!(!seq.is_commit);
        assert_eq!(seq.producer_state.offset, 100, "offset unchanged on extend");
        s.commit(0, p1, seq);

        // ContinueDuplicate: filtered out entirely.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(15, 0), CONTINUE, 200, 250),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(!seq.is_commit);

        // AckCommit: not enqueued, triggers commit/flush, offset becomes committed.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 250, 300),
        )
        .unwrap();
        assert!(!seq.is_append, "ACKs are never appended");
        assert!(seq.is_commit, "AckCommit triggers flush");
        assert_eq!(
            seq.producer_state.offset, -300,
            "offset = negated committed end"
        );
        s.commit(0, p1, seq);

        // AckDuplicate: no append, no commit (no spurious flush).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 300, 350),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(!seq.is_commit, "AckDuplicate must not trigger flush");

        // Start a new CONTINUE span, then clean rollback (ACK at last_commit clock).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(30, 0), CONTINUE, 350, 400),
        )
        .unwrap();
        assert!(seq.is_append);
        assert_eq!(seq.producer_state.offset, 350, "new span begin");
        s.commit(0, p1, seq);

        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &meta(p1, Clock::from_unix(20, 0), ACK, 400, 450),
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(seq.is_commit, "AckCleanRollback triggers flush");
        assert_eq!(
            seq.producer_state.offset, -450,
            "rollback yields committed offset"
        );
    }

    #[test]
    fn test_sequence_ack_backfill_markers_fold_on_commit() {
        let bindings = vec![test_binding(0, true, None, "/suffix")];
        let mut s = test_state(bindings);

        let p1 = producer(0x01);

        let ResolvedCheckpoint { producers, .. } =
            resolve_checkpoint(vec![checkpoint_entry(&p1, 0)]);
        s.reads.push(ReadState {
            binding_index: 0,
            journal: "test/journal/A".into(),
            truncated_at: Clock::zero(),
            backfill_begin: Clock::zero(),
            backfill_complete: Clock::zero(),
            settled: producers,
            pending: Default::default(),
            read_offset: 0,
            prev_read_offset: 0,
            write_head: 0,
            prev_write_head: 0,
        });

        // A BackfillBegin marker rides on an ACK. In a journal the producer never
        // wrote to (no pending span), it sequences as AckEmpty: it commits, folds
        // its clock into backfill_begin, and is never appended (ACKs never append).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &Meta {
                producer: p1,
                clock: Clock::from_unix(10, 0),
                flags: ACK,
                begin_offset: 100,
                end_offset: 150,
                backfill_event: Some(super::super::read::BackfillEvent::BackfillBegin),
            },
        )
        .unwrap();
        assert!(!seq.is_append, "ACKs never append");
        assert!(seq.is_commit, "AckEmpty commits");
        assert_eq!(
            seq.backfill_begin,
            Clock::from_unix(10, 0),
            "reports its clock"
        );
        assert_eq!(seq.backfill_complete, Clock::zero());
        s.commit(0, p1, seq);
        assert_eq!(s.reads[0].backfill_begin, Clock::from_unix(10, 0));

        // A BackfillComplete marker at a later clock carries the begin boundary it
        // completed as `truncated_at` (so a reader need not have seen the begin).
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &Meta {
                producer: p1,
                clock: Clock::from_unix(20, 0),
                flags: ACK,
                begin_offset: 150,
                end_offset: 200,
                backfill_event: Some(super::super::read::BackfillEvent::BackfillComplete {
                    truncated_at: Clock::from_unix(10, 0),
                }),
            },
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(seq.is_commit);
        assert_eq!(seq.backfill_begin, Clock::zero());
        assert_eq!(seq.backfill_complete, Clock::from_unix(10, 0));
        s.commit(0, p1, seq);
        assert_eq!(s.reads[0].backfill_begin, Clock::from_unix(10, 0));
        assert_eq!(s.reads[0].backfill_complete, Clock::from_unix(10, 0));

        // A conservative re-read replays the same complete ACK (same clock). It
        // sequences as AckDuplicate: no commit, and crucially NO re-fold — the
        // marker must not be re-delivered within an already-resolved checkpoint.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &Meta {
                producer: p1,
                clock: Clock::from_unix(20, 0),
                flags: ACK,
                begin_offset: 200,
                end_offset: 250,
                backfill_event: Some(super::super::read::BackfillEvent::BackfillComplete {
                    truncated_at: Clock::from_unix(10, 0),
                }),
            },
        )
        .unwrap();
        assert!(!seq.is_append);
        assert!(!seq.is_commit, "AckDuplicate suppresses flush");
        assert_eq!(
            seq.backfill_complete,
            Clock::zero(),
            "duplicate does not re-fold"
        );
        s.commit(0, p1, seq);
        assert_eq!(
            s.reads[0].backfill_complete,
            Clock::from_unix(10, 0),
            "unchanged on duplicate"
        );

        // A fresh BackfillBegin ACK at a later clock supersedes the prior begin
        // via the commit-time max fold into the read.
        let seq = sequence(
            &s.reads[0],
            &s.bindings[0],
            &Meta {
                producer: p1,
                clock: Clock::from_unix(30, 0),
                flags: ACK,
                begin_offset: 250,
                end_offset: 300,
                backfill_event: Some(super::super::read::BackfillEvent::BackfillBegin),
            },
        )
        .unwrap();
        assert!(seq.is_commit);
        assert_eq!(seq.backfill_begin, Clock::from_unix(30, 0));
        s.commit(0, p1, seq);
        assert_eq!(s.reads[0].backfill_begin, Clock::from_unix(30, 0));
        assert_eq!(s.reads[0].backfill_complete, Clock::from_unix(10, 0));
    }

    /// Build a passthrough PartitionFilter that accepts any value for the given fields.
    /// The field count must match the partition field segments in the journal suffix.
    fn passthrough_filter(fields: &[&str]) -> PartitionFilter {
        let fields: Vec<String> = fields.iter().map(|f| f.to_string()).collect();
        PartitionFilter::new(&fields, &broker::LabelSelector::default())
    }

    #[test]
    fn test_hint_index_lookup() {
        // Example filter that includes "alpha" category and excludes "bad" region.
        let filter = PartitionFilter::new(
            &["category".to_string(), "region".to_string()],
            &broker::LabelSelector {
                include: Some(labels::build_set(
                    [(
                        "estuary.dev/field/category".to_string(),
                        "alpha".to_string(),
                    )]
                    .into_iter(),
                )),
                exclude: Some(labels::build_set(
                    [("estuary.dev/field/region".to_string(), "bad".to_string())].into_iter(),
                )),
            },
        );

        let cases: Vec<(Vec<(&str, u16, u32, PartitionFilter)>, &str, u32, Vec<u16>)> = vec![
            // Prefix match: anvils has 1 partition field, bananas has 0.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0],
            ),
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "acmeCo/bananas/pivot=00",
                0,
                vec![1],
            ),
            // No matching prefix.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
                ],
                "other/collection/pivot=00",
                0,
                vec![],
            ),
            // Cohort filtering: same prefix, different cohorts.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0],
            ),
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                1,
                vec![1],
            ),
            // Unknown cohort.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                99,
                vec![],
            ),
            // Multiple bindings, same prefix and cohort.
            (
                vec![
                    ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                    ("acmeCo/anvils/", 1, 0, passthrough_filter(&["part"])),
                ],
                "acmeCo/anvils/part=a/pivot=00",
                0,
                vec![0, 1],
            ),
            // Partition filter: "alpha" is included, "eu" not excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=alpha/region=eu/pivot=00",
                0,
                vec![0],
            ),
            // Partition filter: "beta" is not included, "eu" not excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=beta/region=eu/pivot=00",
                0,
                vec![],
            ),
            // Partition filter: "alpha" is included, "bad" is excluded.
            (
                vec![("acmeCo/anvils/", 0, 0, filter.clone())],
                "acmeCo/anvils/category=beta/region=bad/pivot=00",
                0,
                vec![],
            ),
        ];

        let mut out = Vec::new();
        for (entries, journal, cohort, expected) in cases {
            let index = HintIndex::new(entries.into_iter());
            index.lookup(&journal, cohort, &mut out).unwrap();
            out.sort();
            assert_eq!(&out, &expected, "journal={journal}, cohort={cohort}");
        }
    }

    fn test_hint_index() -> HintIndex {
        // anvils has 1 partition field ("part"), bananas has 0.
        HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/bananas/", 1, 0, passthrough_filter(&[])),
            ]
            .into_iter(),
        )
    }

    #[test]
    fn test_extract_causal_hints_round_trip() {
        let index = test_hint_index();
        let mut causal_hints = CausalHints::default();

        let p1 = producer(0x00);
        let p2 = producer(0x02);

        // Build a transaction with two producers across two journals.
        let txn = vec![
            (
                p1,
                Clock::from_u64(100),
                vec![
                    "acmeCo/anvils/part=a/pivot=00".to_string(),
                    "acmeCo/bananas/pivot=00".to_string(),
                ],
            ),
            (
                p2,
                Clock::from_u64(200),
                vec!["acmeCo/anvils/part=a/pivot=00".to_string()],
            ),
        ];

        let journal_acks = publisher::intents::build_transaction_intents(&txn, None);

        // For each journal's first ACK, extract hints into causal_hints.
        // build_transaction_intents returns NDJSON bytes per journal;
        // parse the first line back into a serde_json::Value for hint extraction.
        for (journal, ndjson) in &journal_acks {
            let first_line = ndjson.split(|b| *b == b'\n').next().unwrap();
            let ack: serde_json::Value = serde_json::from_slice(first_line).unwrap();
            let uuid_str = ack["_meta"]["uuid"].as_str().unwrap();
            let (ack_producer, commit_clock, _flags) = uuid::parse_str(uuid_str).unwrap();

            extract_causal_hints(
                &index,
                journal,
                0, // cohort
                0, // producing binding (unused: this index has no shared journals)
                ack_producer,
                commit_clock,
                &ack,
                &mut causal_hints,
            )
            .unwrap();
        }

        // Collect into sorted tuples for deterministic assertion.
        let mut entries: Vec<_> = causal_hints
            .iter()
            .map(|((j, b), hints)| {
                let mut h: Vec<_> = hints.iter().map(|(p, c)| (p, c)).collect();
                h.sort();
                (j.as_ref().to_string(), *b, h)
            })
            .collect();
        entries.sort();

        insta::assert_debug_snapshot!(entries);
    }

    #[test]
    fn test_extract_causal_hints_no_hints_and_decode_error() {
        let index = test_hint_index();
        let p1 = producer(0x00);

        // ACK doc without hints field: causal_hints remains empty.
        let mut causal_hints = CausalHints::default();
        let doc = serde_json::json!({"_meta": {"uuid": "00000000-0000-0000-0000-000000000000"}});
        extract_causal_hints(
            &index,
            "acmeCo/anvils/x",
            0,
            0,
            p1,
            Clock::from_u64(100),
            &doc,
            &mut causal_hints,
        )
        .unwrap();
        assert!(causal_hints.is_empty());

        // Malformed hints field: returns decode error.
        let doc = serde_json::json!({"hints": [{"j": "not-an-array", "p": []}]});
        let err = extract_causal_hints(
            &index,
            "acmeCo/anvils/x",
            0,
            0,
            p1,
            Clock::from_u64(100),
            &doc,
            &mut causal_hints,
        )
        .unwrap_err();
        assert!(
            format!("{err}").contains("decoding causal hint"),
            "error should mention decoding: {err}"
        );
    }

    #[test]
    fn test_extract_causal_hints_self_projection() {
        // Common 1:1 case: each journal-prefix maps to one binding → no projection.
        assert!(!test_hint_index().cohort_shares_journal);

        // Two bindings (0, 1) of cohort 0 read the same anvils prefix; binding 2
        // reads a different prefix. Sharing is detected.
        let index = HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 1, 0, passthrough_filter(&["part"])),
                ("acmeCo/bananas/", 2, 0, passthrough_filter(&[])),
            ]
            .into_iter(),
        );
        assert!(index.cohort_shares_journal);

        // Same-cohort bindings need not be adjacent under the (prefix, binding)
        // sort: bindings 0 and 2 share the anvils prefix and cohort 0, while
        // binding 1 (cohort 1) sorts between them (priorities `[0, 1, 0]`).
        // Sharing must still be detected.
        let index_interleaved = HintIndex::new(
            [
                ("acmeCo/anvils/", 0, 0, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 1, 1, passthrough_filter(&["part"])),
                ("acmeCo/anvils/", 2, 0, passthrough_filter(&["part"])),
            ]
            .into_iter(),
        );
        assert!(index_interleaved.cohort_shares_journal);

        let p1 = producer(0x00);
        let mut causal_hints = CausalHints::default();

        // An ACK read by binding 0 from the anvils journal, carrying NO doc hints —
        // exactly the case a single-producer collection ACK presents to a
        // materialization that reads it under two bindings.
        let ack = serde_json::json!({"is_ack": true});
        extract_causal_hints(
            &index,
            "acmeCo/anvils/part=a/pivot=00",
            0, // cohort
            0, // producing binding
            p1,
            Clock::from_u64(100),
            &ack,
            &mut causal_hints,
        )
        .unwrap();

        // The self-hint lands on the *peer* binding (1) that also reads anvils —
        // never on the producing binding (0), nor on the unrelated bananas
        // binding (2). So the checkpoint can't advance binding 0 past this commit
        // until binding 1's read of anvils also reaches it.
        let entries: Vec<_> = causal_hints
            .iter()
            .map(|((j, b), hints)| (j.as_ref().to_string(), *b, hints.clone()))
            .collect();
        assert_eq!(
            entries,
            vec![(
                "acmeCo/anvils/part=a/pivot=00".to_string(),
                1u16,
                vec![(p1, Clock::from_u64(100))],
            )],
        );
    }
}
