[package]
name = "typescript"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
json = { path = "../json" }
doc = { path = "../doc" }

lazy_static = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }