[package]
name = "typescript"
version = "0.0.0"
authors = ["Estuary Technologies, Inc"]
edition = "2021"

[dependencies]
json = { path = "../json" }
doc = { path = "../doc" }

lazy_static = { workspace = true }
regex = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }