[package]
name = "ops-catalog"
version.workspace = true
rust-version.workspace = true
edition.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true

[[bin]]
name = "flow-ops-catalog"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
derivative = { workspace = true }
dirs = { workspace = true }
handlebars = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
insta = { workspace = true }
tempfile = { workspace = true }