version: "3.7"

services:
  postgres:
    image: postgres:latest
    command: ["postgres", "-c", "wal_level=logical"]
    volumes: ["postgres_data:/var/lib/postgresql/data"]
    environment:
      POSTGRES_USER: flow
      POSTGRES_PASSWORD: flow
      POSTGRES_DB: control_development
    ports: ['5432:5432']

volumes:
  postgres_data: {}
