#!/usr/bin/env bash
set -euo pipefail

#MISE description="Installs extra packages NOT present on GitHub Actions Ubuntu Runners"
#MISE depends=["bootstrap:apt-update"]
#MISE sources=["."]

# Packages we use which are NOT already installed on GitHub Actions Ubuntu runners.
# Packages already on GitHub Actions CI runners should go in apt-packages-ci-base.
# See: https://github.com/actions/runner-images?tab=readme-ov-file

sudo DEBIAN_FRONTEND=noninteractive apt-get install -y \
  age \
  g++-14 \
  gcc-14 \
  libjemalloc-dev \
  libsnappy-dev \
  musl-tools \
  postgresql-client-16 \
  postgresql-client-common \
  python3-venv \
  python3-poetry \

# Configure system default compilers and linkers using update-alternatives.
sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
