#!/usr/bin/env bash
set -euo pipefail

#MISE description="Writes IDE settings for VSCode Remote SSH and Zed"

# VSCode Remote SSH settings.
VSCODE_SETTINGS="${HOME}/.vscode-server/data/Machine/settings.json"

mkdir -p $(dirname ${VSCODE_SETTINGS})
cat > ${VSCODE_SETTINGS} << EOF
{
    "go.goroot": "${GOROOT}",
    "go.toolsEnvVars": {
        "CGO_LDFLAGS": "${CGO_LDFLAGS}",
        "CGO_CFLAGS": "${CGO_CFLAGS}",
        "CGO_CPPFLAGS": "${CGO_CPPFLAGS}",
        "PATH": "${PATH}:${CARGO_TARGET_DIR}/debug/:${CARGO_TARGET_DIR}/$(uname -m)-unknown-linux-musl/debug/",
    },
    "rust-analyzer.cargo.extraEnv": {
        "CARGO_TARGET_DIR": "${CARGO_TARGET_DIR}",
        "JEMALLOC_OVERRIDE": "${JEMALLOC_OVERRIDE}",
        "PATH": "${PATH}",
        "ROCKSDB_INCLUDE_DIR": "${ROCKSDB_INCLUDE_DIR}",
        "ROCKSDB_LIB_DIR": "${ROCKSDB_LIB_DIR}",
        "ROCKSDB_VERSION": "${ROCKSDB_VERSION}",
        "RUSTFLAGS": "${RUSTFLAGS}",
        "SNAPPY_LIB_DIR": "${SNAPPY_LIB_DIR}",
        "SNAPPY_STATIC": "${SNAPPY_STATIC}",
    },
    "rust-analyzer.runnables.extraEnv": {
        "CARGO_TARGET_DIR": "${CARGO_TARGET_DIR}",
        "JEMALLOC_OVERRIDE": "${JEMALLOC_OVERRIDE}",
        "PATH": "${PATH}",
        "ROCKSDB_INCLUDE_DIR": "${ROCKSDB_INCLUDE_DIR}",
        "ROCKSDB_LIB_DIR": "${ROCKSDB_LIB_DIR}",
        "ROCKSDB_VERSION": "${ROCKSDB_VERSION}",
        "RUSTFLAGS": "${RUSTFLAGS}",
        "SNAPPY_LIB_DIR": "${SNAPPY_LIB_DIR}",
        "SNAPPY_STATIC": "${SNAPPY_STATIC}",
    },
    "lldb.launch.env": {
        "DATABASE_URL": "postgresql://postgres:postgres@localhost:5432/postgres",
        "SOPS_AGE_KEY": "AGE-SECRET-KEY-1UX6ZHA36JJZCFCV9U7FVHZZECHCCKA8NCFT27L68HV0NPRQ2V5ZSRKJJPU"
    },

    // TODO(johnny): Remove this Go dependency altogether!
    "go.buildTags": "libsqlite3",
    // We're running in VMs with restricted memory, so don't index crates
    // that aren't actively being worked on by the user.
    "rust-analyzer.cachePriming.enable": false
}
EOF

echo "Wrote VSCode settings: ${VSCODE_SETTINGS}"

# Zed editor settings.
ZED_SETTINGS="${HOME}/.config/zed/settings.json"

mkdir -p $(dirname ${ZED_SETTINGS})
cat > ${ZED_SETTINGS} << EOF
{
    "lsp": {
        "gopls": {
            "initialization_options": {
                "buildFlags": ["-tags=libsqlite3"]
            },
            "binary": {
                "env": {
                    "GOROOT": "${GOROOT}",
                    "CGO_LDFLAGS": "${CGO_LDFLAGS}",
                    "CGO_CFLAGS": "${CGO_CFLAGS}",
                    "CGO_CPPFLAGS": "${CGO_CPPFLAGS}",
                    "PATH": "${PATH}:${CARGO_TARGET_DIR}/debug/:${CARGO_TARGET_DIR}/$(uname -m)-unknown-linux-musl/debug/"
                }
            }
        },
        "rust-analyzer": {
            "initialization_options": {
                "cargo": {
                    "extraEnv": {
                        "CARGO_TARGET_DIR": "${CARGO_TARGET_DIR}",
                        "JEMALLOC_OVERRIDE": "${JEMALLOC_OVERRIDE}",
                        "PATH": "${PATH}",
                        "ROCKSDB_INCLUDE_DIR": "${ROCKSDB_INCLUDE_DIR}",
                        "ROCKSDB_LIB_DIR": "${ROCKSDB_LIB_DIR}",
                        "ROCKSDB_VERSION": "${ROCKSDB_VERSION}",
                        "RUSTFLAGS": "${RUSTFLAGS}",
                        "SNAPPY_LIB_DIR": "${SNAPPY_LIB_DIR}",
                        "SNAPPY_STATIC": "${SNAPPY_STATIC}"
                    }
                },
                "runnables": {
                    "extraEnv": {
                        "CARGO_TARGET_DIR": "${CARGO_TARGET_DIR}",
                        "JEMALLOC_OVERRIDE": "${JEMALLOC_OVERRIDE}",
                        "PATH": "${PATH}",
                        "ROCKSDB_INCLUDE_DIR": "${ROCKSDB_INCLUDE_DIR}",
                        "ROCKSDB_LIB_DIR": "${ROCKSDB_LIB_DIR}",
                        "ROCKSDB_VERSION": "${ROCKSDB_VERSION}",
                        "RUSTFLAGS": "${RUSTFLAGS}",
                        "SNAPPY_LIB_DIR": "${SNAPPY_LIB_DIR}",
                        "SNAPPY_STATIC": "${SNAPPY_STATIC}"
                    }
                },
                "cachePriming": {
                    "enable": false
                }
            }
        }
    }
}
EOF

echo "Wrote Zed settings: ${ZED_SETTINGS}"
