-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

ALTER TABLE IF EXISTS public.catalog_stats
    OWNER TO stats_loader;

ALTER TABLE IF EXISTS public.catalog_stats DETACH PARTITION catalog_stat_partitions.estuary_stats;
ALTER TABLE IF EXISTS public.catalog_stats DETACH PARTITION catalog_stat_partitions.ops_stats;
DROP TABLE IF EXISTS catalog_stat_partitions.flow_checkpoints_v1 CASCADE;
DROP TABLE IF EXISTS catalog_stat_partitions.flow_materializations_v2 CASCADE;