/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AutoDiscoverOutcome {
    /// Bindings that were added to the capture.
    #[serde(rename = "added", skip_serializing_if = "Option::is_none")]
    pub added: Option<Vec<models::DiscoverChange>>,
    /// Errors that occurred during the discovery or evolution process.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<Vec<models::Error>>,
    /// Bindings that were modified, either to change the schema or the collection key.
    #[serde(rename = "modified", skip_serializing_if = "Option::is_none")]
    pub modified: Option<Vec<models::DiscoverChange>>,
    #[serde(rename = "publish_result", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub publish_result: Option<Option<Box<models::JobStatus>>>,
    /// Collections that were re-created due to the collection key having changed.
    #[serde(rename = "re_created_collections", skip_serializing_if = "Option::is_none")]
    pub re_created_collections: Option<Vec<models::EvolvedCollection>>,
    /// Bindings that were removed because they no longer appear in the source system.
    #[serde(rename = "removed", skip_serializing_if = "Option::is_none")]
    pub removed: Option<Vec<models::DiscoverChange>>,
    /// Time at which the disocver was attempted
    #[serde(rename = "ts")]
    pub ts: String,
}

impl AutoDiscoverOutcome {
    pub fn new(ts: String) -> AutoDiscoverOutcome {
        AutoDiscoverOutcome {
            added: None,
            errors: None,
            modified: None,
            publish_result: None,
            re_created_collections: None,
            removed: None,
            ts,
        }
    }
}

