/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IncompatibleCollection {
    #[serde(rename = "affected_materializations", skip_serializing_if = "Option::is_none")]
    pub affected_materializations: Option<Vec<models::AffectedConsumer>>,
    #[serde(rename = "collection")]
    pub collection: String,
    /// Reasons why the collection would need to be re-created in order for a publication of the draft spec to succeed.
    #[serde(rename = "requires_recreation", skip_serializing_if = "Option::is_none")]
    pub requires_recreation: Option<Vec<models::ReCreateReason>>,
}

impl IncompatibleCollection {
    pub fn new(collection: String) -> IncompatibleCollection {
        IncompatibleCollection {
            affected_materializations: None,
            collection,
            requires_recreation: None,
        }
    }
}

