/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JobStatusOneOf3 {
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl JobStatusOneOf3 {
    pub fn new(r#type: Type) -> JobStatusOneOf3 {
        JobStatusOneOf3 {
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "publishFailed")]
    PublishFailed,
}

impl Default for Type {
    fn default() -> Type {
        Self::PublishFailed
    }
}

