/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RejectedField {
    #[serde(rename = "field")]
    pub field: String,
    #[serde(rename = "reason")]
    pub reason: String,
}

impl RejectedField {
    pub fn new(field: String, reason: String) -> RejectedField {
        RejectedField {
            field,
            reason,
        }
    }
}

