/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusResponseControllerStatusOneOf : Status of a capture controller
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatusResponseControllerStatusOneOf {
    #[serde(rename = "activation", skip_serializing_if = "Option::is_none")]
    pub activation: Option<Box<models::ActivationStatus>>,
    #[serde(rename = "auto_discover", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub auto_discover: Option<Option<Box<models::AutoDiscoverStatus>>>,
    #[serde(rename = "publications", skip_serializing_if = "Option::is_none")]
    pub publications: Option<Box<models::PublicationStatus>>,
    #[serde(rename = "type")]
    pub r#type: Type,
}

impl StatusResponseControllerStatusOneOf {
    /// Status of a capture controller
    pub fn new(r#type: Type) -> StatusResponseControllerStatusOneOf {
        StatusResponseControllerStatusOneOf {
            activation: None,
            auto_discover: None,
            publications: None,
            r#type,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Capture")]
    Capture,
}

impl Default for Type {
    fn default() -> Type {
        Self::Capture
    }
}

