/*
 * Flow Control Plane V0 API
 *
 * some description here
 *
 * The version of the OpenAPI document: 
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StatusResponseControllerStatus : The controller status json.
/// The controller status json.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum StatusResponseControllerStatus {
    StatusResponseControllerStatusOneOf(Box<models::StatusResponseControllerStatusOneOf>),
    StatusResponseControllerStatusOneOf1(Box<models::StatusResponseControllerStatusOneOf1>),
    StatusResponseControllerStatusOneOf2(Box<models::StatusResponseControllerStatusOneOf2>),
    StatusResponseControllerStatusOneOf3(Box<models::StatusResponseControllerStatusOneOf3>),
}

impl Default for StatusResponseControllerStatus {
    fn default() -> Self {
        Self::StatusResponseControllerStatusOneOf(Default::default())
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Capture")]
    Capture,
    #[serde(rename = "Collection")]
    Collection,
    #[serde(rename = "Materialization")]
    Materialization,
    #[serde(rename = "Test")]
    Test,
}

impl Default for Type {
    fn default() -> Type {
        Self::Capture
    }
}

